In [2]:
import netCDF4 as nc
import numpy as np

# Load the first file
import os
files = sorted(os.listdir(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\raw\merra"))
filepath = fr"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\raw\merra" + "/" + files[0]

ds = nc.Dataset(filepath)

# Structure
print("=" * 50)
print("FILE:", files[0])
print("=" * 50)

# Dimensions
print("\nDIMENSIONS:")
for dim in ds.dimensions:
    print(f"  {dim}: {len(ds.dimensions[dim])}")

# Variables
print("\nVARIABLES:")
for var in ds.variables:
    v = ds.variables[var]
    print(f"  {var}: shape={v.shape}, dtype={v.dtype}")
    if hasattr(v, 'units'):
        print(f"    units: {v.units}")
    if hasattr(v, 'long_name'):
        print(f"    long_name: {v.long_name}")

# Head — first row of each variable
print("\nHEAD (first values):")
for var in ds.variables:
    v = ds.variables[var]
    try:
        print(f"  {var}: {v[0].data.flatten()[:5]}")
    except:
        pass

ds.close()

==================================================
FILE: M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230101_subsetted.nc4
==================================================

DIMENSIONS:
  lon: 48
  time: 24
  lat: 62

VARIABLES:
  lon: shape=(48,), dtype=float64
    units: degrees_east
    long_name: longitude
  time: shape=(24,), dtype=int32
    units: minutes since 2023-01-01 00:30:00
    long_name: time
  lat: shape=(62,), dtype=float64
    units: degrees_north
    long_name: latitude
  ULML: shape=(24, 62, 48), dtype=float32
    units: m s-1
    long_name: surface_eastward_wind
  TLML: shape=(24, 62, 48), dtype=float32
    units: K
    long_name: surface_air_temperature
  PRECTOT: shape=(24, 62, 48), dtype=float32
    units: kg m-2 s-1
    long_name: total_precipitation
  SPEED: shape=(24, 62, 48), dtype=float32
    units: m s-1
    long_name: surface_wind_speed
  QLML: shape=(24, 62, 48), dtype=float32
    units: 1
    long_name: surface_specific_humidity
  PBLH: shape=(24, 62, 48), dtype=float32
    units: m
    long_name: planetary_boundary_layer_height
  VLML: shape=(24, 62, 48), dtype=float32
    units: m s-1
    long_name: surface_northward_wind

HEAD (first values):
  lon: [68.125]
  time: [0]
  lat: [6.5]
  ULML: [-3.9770043 -3.8676293 -3.6156762 -3.2777855 -2.9623559]
  TLML: [299.25107 299.2042  299.29794 299.59482 299.5167 ]
  PRECTOT: [9.6997246e-07 6.4400956e-07 1.5966361e-07 8.3819032e-08 8.1839971e-08]
  SPEED: [5.2146177 5.0368834 4.825946  4.607196  4.4431334]
  QLML: [0.01638359 0.01608604 0.01559776 0.01480812 0.01481575]
  PBLH: [ 768.7152  752.2152  818.9652 1035.7152 1085.7152]
  VLML: [-3.3672276 -3.2231846 -3.1924229 -3.2353916 -3.307169 ]

C:\Users\kesha\AppData\Local\Temp\ipykernel_26788\1680752913.py:36: RuntimeWarning: invalid value encountered in cast
  print(f"  {var}: {v[0].data.flatten()[:5]}")
C:\Users\kesha\AppData\Local\Temp\ipykernel_26788\1680752913.py:36: UserWarning: WARNING: valid_range not used since it
cannot be safely cast to variable data type
  print(f"  {var}: {v[0].data.flatten()[:5]}")

In [5]:
import netCDF4 as nc
import numpy as np

file_path = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\raw\merra\M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230101_subsetted.nc4"

ds = nc.Dataset(file_path)

print("="*50)
print(f"FILE: {file_path}")
print("="*50)

print("\nDIMENSIONS:")
for dim in ds.dimensions:
    print(f"  {dim}: {len(ds.dimensions[dim])}")

print("\nVARIABLES:")
for var in ds.variables:
    v = ds.variables[var]
    print(f"  {var}: shape={v.shape}, dtype={v.dtype}")
    
    for attr in v.ncattrs():
        print(f"    {attr}: {getattr(v, attr)}")

print("\nHEAD (first values safely):")

for var in ds.variables:
    v = ds.variables[var]
    
    try:
        # Read safely without forcing cast
        data = v[:]

        # Flatten safely
        if hasattr(data, "compressed"):  
            # masked array → remove masked values
            flat = data.compressed()
        else:
            flat = data.flatten()
        
        print(f"  {var}: {flat[:5]}")
    
    except Exception as e:
        print(f"  {var}: ERROR → {e}")

ds.close()

==================================================
FILE: C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\raw\merra\M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230101_subsetted.nc4
==================================================

DIMENSIONS:
  lon: 48
  time: 24
  lat: 62

VARIABLES:
  lon: shape=(48,), dtype=float64
    long_name: longitude
    units: degrees_east
    vmax: 999999986991104.0
    vmin: -999999986991104.0
    valid_range: [-1.e+15  1.e+15]
  time: shape=(24,), dtype=int32
    long_name: time
    units: minutes since 2023-01-01 00:30:00
    time_increment: 10000
    begin_date: 20230101
    begin_time: 3000
    vmax: 999999986991104.0
    vmin: -999999986991104.0
    valid_range: [-1.e+15  1.e+15]
  lat: shape=(62,), dtype=float64
    long_name: latitude
    units: degrees_north
    vmax: 999999986991104.0
    vmin: -999999986991104.0
    valid_range: [-1.e+15  1.e+15]
  ULML: shape=(24, 62, 48), dtype=float32
    long_name: surface_eastward_wind
    units: m s-1
    _FillValue: 999999986991104.0
    missing_value: 999999986991104.0
    fmissing_value: 999999986991104.0
    scale_factor: 1.0
    add_offset: 0.0
    standard_name: surface_eastward_wind
    vmax: 999999986991104.0
    vmin: -999999986991104.0
    valid_range: [-1.e+15  1.e+15]
  TLML: shape=(24, 62, 48), dtype=float32
    long_name: surface_air_temperature
    units: K
    _FillValue: 999999986991104.0
    missing_value: 999999986991104.0
    fmissing_value: 999999986991104.0
    scale_factor: 1.0
    add_offset: 0.0
    standard_name: surface_air_temperature
    vmax: 999999986991104.0
    vmin: -999999986991104.0
    valid_range: [-1.e+15  1.e+15]
  PRECTOT: shape=(24, 62, 48), dtype=float32
    long_name: total_precipitation
    units: kg m-2 s-1
    _FillValue: 999999986991104.0
    missing_value: 999999986991104.0
    fmissing_value: 999999986991104.0
    scale_factor: 1.0
    add_offset: 0.0
    standard_name: total_precipitation
    vmax: 999999986991104.0
    vmin: -999999986991104.0
    valid_range: [-1.e+15  1.e+15]
  SPEED: shape=(24, 62, 48), dtype=float32
    long_name: surface_wind_speed
    units: m s-1
    _FillValue: 999999986991104.0
    missing_value: 999999986991104.0
    fmissing_value: 999999986991104.0
    scale_factor: 1.0
    add_offset: 0.0
    standard_name: surface_wind_speed
    vmax: 999999986991104.0
    vmin: -999999986991104.0
    valid_range: [-1.e+15  1.e+15]
  QLML: shape=(24, 62, 48), dtype=float32
    long_name: surface_specific_humidity
    units: 1
    _FillValue: 999999986991104.0
    missing_value: 999999986991104.0
    fmissing_value: 999999986991104.0
    scale_factor: 1.0
    add_offset: 0.0
    standard_name: surface_specific_humidity
    vmax: 999999986991104.0
    vmin: -999999986991104.0
    valid_range: [-1.e+15  1.e+15]
  PBLH: shape=(24, 62, 48), dtype=float32
    long_name: planetary_boundary_layer_height
    units: m
    _FillValue: 999999986991104.0
    missing_value: 999999986991104.0
    fmissing_value: 999999986991104.0
    scale_factor: 1.0
    add_offset: 0.0
    standard_name: planetary_boundary_layer_height
    vmax: 999999986991104.0
    vmin: -999999986991104.0
    valid_range: [-1.e+15  1.e+15]
  VLML: shape=(24, 62, 48), dtype=float32
    long_name: surface_northward_wind
    units: m s-1
    _FillValue: 999999986991104.0
    missing_value: 999999986991104.0
    fmissing_value: 999999986991104.0
    scale_factor: 1.0
    add_offset: 0.0
    standard_name: surface_northward_wind
    vmax: 999999986991104.0
    vmin: -999999986991104.0
    valid_range: [-1.e+15  1.e+15]

HEAD (first values safely):
  lon: [68.125 68.75  69.375 70.    70.625]
  time: [  0  60 120 180 240]
  lat: [6.5 7.  7.5 8.  8.5]
  ULML: [-3.9770043 -3.8676293 -3.6156762 -3.2777855 -2.9623559]
  TLML: [299.25107 299.2042  299.29794 299.59482 299.5167 ]
  PRECTOT: [9.6997246e-07 6.4400956e-07 1.5966361e-07 8.3819032e-08 8.1839971e-08]
  SPEED: [5.2146177 5.0368834 4.825946  4.607196  4.4431334]
  QLML: [0.01638359 0.01608604 0.01559776 0.01480812 0.01481575]
  PBLH: [ 768.7152  752.2152  818.9652 1035.7152 1085.7152]
  VLML: [-3.3672276 -3.2231846 -3.1924229 -3.2353916 -3.307169 ]

C:\Users\kesha\AppData\Local\Temp\ipykernel_19548\2510362332.py:31: RuntimeWarning: invalid value encountered in cast
  data = v[:]
C:\Users\kesha\AppData\Local\Temp\ipykernel_19548\2510362332.py:31: UserWarning: WARNING: valid_range not used since it
cannot be safely cast to variable data type
  data = v[:]

In [3]:
import netCDF4 as nc
import numpy as np
import pandas as pd
import os
from datetime import datetime, timedelta
import pyarrow as pa
import pyarrow.parquet as pq

DATA_DIR = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\raw\merra"
OUTPUT_FILE = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\merra_merged.parquet"

VARIABLES = ["PBLH", "TLML", "QLML", "ULML", "VLML", "SPEED", "PRECTOT"]

files = sorted([f for f in os.listdir(DATA_DIR) if f.endswith(".nc4")])
print(f"Found {len(files)} files\n")

parquet_writer = None

for i, fname in enumerate(files):
    try:
        ds = nc.Dataset(os.path.join(DATA_DIR, fname))

        lons = ds.variables["lon"][:]
        lats = ds.variables["lat"][:]
        times = ds.variables["time"]

        # Time parsing
        time_units = times.units
        base_time_str = time_units.split("since ")[-1]
        base_time = datetime.strptime(base_time_str.strip(), "%Y-%m-%d %H:%M:%S")
        timestamps = [base_time + timedelta(minutes=int(t)) for t in times[:]]

        lon2d, lat2d = np.meshgrid(lons, lats)
        lon_flat = lon2d.flatten()
        lat_flat = lat2d.flatten()

        for t_idx, timestamp in enumerate(timestamps):
            data_dict = {
                "datetime": np.full_like(lon_flat, timestamp, dtype=object),
                "latitude": lat_flat,
                "longitude": lon_flat,
            }

            for var in VARIABLES:
                if var in ds.variables:
                    data = ds.variables[var][t_idx, :, :].filled(np.nan).flatten()
                    data_dict[var] = data

            df = pd.DataFrame(data_dict)

            table = pa.Table.from_pandas(df)

            # Initialize writer only once
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(OUTPUT_FILE, table.schema)

            parquet_writer.write_table(table)

        ds.close()
        print(f"[{i+1}/{len(files)}] {fname} ✅")

    except Exception as e:
        print(f"[{i+1}/{len(files)}] {fname} ❌ {e}")

# Close writer
if parquet_writer:
    parquet_writer.close()

print(f"\n✅ Single Parquet saved at: {OUTPUT_FILE}")

Found 730 files

C:\Users\kesha\AppData\Local\Temp\ipykernel_26788\3546523905.py:31: RuntimeWarning: invalid value encountered in cast
  timestamps = [base_time + timedelta(minutes=int(t)) for t in times[:]]
C:\Users\kesha\AppData\Local\Temp\ipykernel_26788\3546523905.py:31: UserWarning: WARNING: valid_range not used since it
cannot be safely cast to variable data type
  timestamps = [base_time + timedelta(minutes=int(t)) for t in times[:]]

[1/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230101_subsetted.nc4 ✅
[2/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230102_subsetted.nc4 ✅
[3/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230103_subsetted.nc4 ✅
[4/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230104_subsetted.nc4 ✅
[5/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230105_subsetted.nc4 ✅
[6/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230106_subsetted.nc4 ✅
[7/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230107_subsetted.nc4 ✅
[8/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230108_subsetted.nc4 ✅
[9/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230109_subsetted.nc4 ✅
[10/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230110_subsetted.nc4 ✅
[11/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230111_subsetted.nc4 ✅
[12/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230112_subsetted.nc4 ✅
[13/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230113_subsetted.nc4 ✅
[14/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230114_subsetted.nc4 ✅
[15/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230115_subsetted.nc4 ✅
[16/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230116_subsetted.nc4 ✅
[17/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230117_subsetted.nc4 ✅
[18/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230118_subsetted.nc4 ✅
[19/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230119_subsetted.nc4 ✅
[20/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230120_subsetted.nc4 ✅
[21/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230121_subsetted.nc4 ✅
[22/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230122_subsetted.nc4 ✅
[23/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230123_subsetted.nc4 ✅
[24/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230124_subsetted.nc4 ✅
[25/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230125_subsetted.nc4 ✅
[26/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230126_subsetted.nc4 ✅
[27/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230127_subsetted.nc4 ✅
[28/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230128_subsetted.nc4 ✅
[29/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230129_subsetted.nc4 ✅
[30/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230130_subsetted.nc4 ✅
[31/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230131_subsetted.nc4 ✅
[32/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230201_subsetted.nc4 ✅
[33/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230202_subsetted.nc4 ✅
[34/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230203_subsetted.nc4 ✅
[35/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230204_subsetted.nc4 ✅
[36/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230205_subsetted.nc4 ✅
[37/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230206_subsetted.nc4 ✅
[38/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230207_subsetted.nc4 ✅
[39/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230208_subsetted.nc4 ✅
[40/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230209_subsetted.nc4 ✅
[41/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230210_subsetted.nc4 ✅
[42/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230211_subsetted.nc4 ✅
[43/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230212_subsetted.nc4 ✅
[44/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230213_subsetted.nc4 ✅
[45/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230214_subsetted.nc4 ✅
[46/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230215_subsetted.nc4 ✅
[47/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230216_subsetted.nc4 ✅
[48/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230217_subsetted.nc4 ✅
[49/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230218_subsetted.nc4 ✅
[50/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230219_subsetted.nc4 ✅
[51/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230220_subsetted.nc4 ✅
[52/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230221_subsetted.nc4 ✅
[53/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230222_subsetted.nc4 ✅
[54/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230223_subsetted.nc4 ✅
[55/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230224_subsetted.nc4 ✅
[56/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230225_subsetted.nc4 ✅
[57/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230226_subsetted.nc4 ✅
[58/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230227_subsetted.nc4 ✅
[59/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230228_subsetted.nc4 ✅
[60/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230301_subsetted.nc4 ✅
[61/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230302_subsetted.nc4 ✅
[62/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230303_subsetted.nc4 ✅
[63/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230304_subsetted.nc4 ✅
[64/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230305_subsetted.nc4 ✅
[65/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230306_subsetted.nc4 ✅
[66/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230307_subsetted.nc4 ✅
[67/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230308_subsetted.nc4 ✅
[68/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230309_subsetted.nc4 ✅
[69/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230310_subsetted.nc4 ✅
[70/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230311_subsetted.nc4 ✅
[71/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230312_subsetted.nc4 ✅
[72/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230313_subsetted.nc4 ✅
[73/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230314_subsetted.nc4 ✅
[74/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230315_subsetted.nc4 ✅
[75/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230316_subsetted.nc4 ✅
[76/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230317_subsetted.nc4 ✅
[77/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230318_subsetted.nc4 ✅
[78/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230319_subsetted.nc4 ✅
[79/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230320_subsetted.nc4 ✅
[80/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230321_subsetted.nc4 ✅
[81/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230322_subsetted.nc4 ✅
[82/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230323_subsetted.nc4 ✅
[83/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230324_subsetted.nc4 ✅
[84/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230325_subsetted.nc4 ✅
[85/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230326_subsetted.nc4 ✅
[86/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230327_subsetted.nc4 ✅
[87/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230328_subsetted.nc4 ✅
[88/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230329_subsetted.nc4 ✅
[89/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230330_subsetted.nc4 ✅
[90/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230331_subsetted.nc4 ✅
[91/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230401_subsetted.nc4 ✅
[92/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230402_subsetted.nc4 ✅
[93/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230403_subsetted.nc4 ✅
[94/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230404_subsetted.nc4 ✅
[95/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230405_subsetted.nc4 ✅
[96/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230406_subsetted.nc4 ✅
[97/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230407_subsetted.nc4 ✅
[98/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230408_subsetted.nc4 ✅
[99/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230409_subsetted.nc4 ✅
[100/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230410_subsetted.nc4 ✅
[101/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230411_subsetted.nc4 ✅
[102/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230412_subsetted.nc4 ✅
[103/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230413_subsetted.nc4 ✅
[104/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230414_subsetted.nc4 ✅
[105/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230415_subsetted.nc4 ✅
[106/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230416_subsetted.nc4 ✅
[107/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230417_subsetted.nc4 ✅
[108/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230418_subsetted.nc4 ✅
[109/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230419_subsetted.nc4 ✅
[110/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230420_subsetted.nc4 ✅
[111/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230421_subsetted.nc4 ✅
[112/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230422_subsetted.nc4 ✅
[113/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230423_subsetted.nc4 ✅
[114/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230424_subsetted.nc4 ✅
[115/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230425_subsetted.nc4 ✅
[116/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230426_subsetted.nc4 ✅
[117/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230427_subsetted.nc4 ✅
[118/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230428_subsetted.nc4 ✅
[119/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230429_subsetted.nc4 ✅
[120/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230430_subsetted.nc4 ✅
[121/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230501_subsetted.nc4 ✅
[122/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230502_subsetted.nc4 ✅
[123/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230503_subsetted.nc4 ✅
[124/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230504_subsetted.nc4 ✅
[125/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230505_subsetted.nc4 ✅
[126/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230506_subsetted.nc4 ✅
[127/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230507_subsetted.nc4 ✅
[128/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230508_subsetted.nc4 ✅
[129/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230509_subsetted.nc4 ✅
[130/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230510_subsetted.nc4 ✅
[131/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230511_subsetted.nc4 ✅
[132/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230512_subsetted.nc4 ✅
[133/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230513_subsetted.nc4 ✅
[134/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230514_subsetted.nc4 ✅
[135/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230515_subsetted.nc4 ✅
[136/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230516_subsetted.nc4 ✅
[137/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230517_subsetted.nc4 ✅
[138/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230518_subsetted.nc4 ✅
[139/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230519_subsetted.nc4 ✅
[140/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230520_subsetted.nc4 ✅
[141/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230521_subsetted.nc4 ✅
[142/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230522_subsetted.nc4 ✅
[143/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230523_subsetted.nc4 ✅
[144/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230524_subsetted.nc4 ✅
[145/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230525_subsetted.nc4 ✅
[146/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230526_subsetted.nc4 ✅
[147/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230527_subsetted.nc4 ✅
[148/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230528_subsetted.nc4 ✅
[149/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230529_subsetted.nc4 ✅
[150/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230530_subsetted.nc4 ✅
[151/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230531_subsetted.nc4 ✅
[152/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230601_subsetted.nc4 ✅
[153/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230602_subsetted.nc4 ✅
[154/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230603_subsetted.nc4 ✅
[155/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230604_subsetted.nc4 ✅
[156/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230605_subsetted.nc4 ✅
[157/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230606_subsetted.nc4 ✅
[158/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230607_subsetted.nc4 ✅
[159/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230608_subsetted.nc4 ✅
[160/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230609_subsetted.nc4 ✅
[161/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230610_subsetted.nc4 ✅
[162/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230611_subsetted.nc4 ✅
[163/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230612_subsetted.nc4 ✅
[164/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230613_subsetted.nc4 ✅
[165/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230614_subsetted.nc4 ✅
[166/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230615_subsetted.nc4 ✅
[167/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230616_subsetted.nc4 ✅
[168/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230617_subsetted.nc4 ✅
[169/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230618_subsetted.nc4 ✅
[170/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230619_subsetted.nc4 ✅
[171/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230620_subsetted.nc4 ✅
[172/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230621_subsetted.nc4 ✅
[173/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230622_subsetted.nc4 ✅
[174/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230623_subsetted.nc4 ✅
[175/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230624_subsetted.nc4 ✅
[176/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230625_subsetted.nc4 ✅
[177/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230626_subsetted.nc4 ✅
[178/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230627_subsetted.nc4 ✅
[179/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230628_subsetted.nc4 ✅
[180/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230629_subsetted.nc4 ✅
[181/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230630_subsetted.nc4 ✅
[182/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230701_subsetted.nc4 ✅
[183/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230702_subsetted.nc4 ✅
[184/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230703_subsetted.nc4 ✅
[185/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230704_subsetted.nc4 ✅
[186/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230705_subsetted.nc4 ✅
[187/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230706_subsetted.nc4 ✅
[188/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230707_subsetted.nc4 ✅
[189/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230708_subsetted.nc4 ✅
[190/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230709_subsetted.nc4 ✅
[191/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230710_subsetted.nc4 ✅
[192/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230711_subsetted.nc4 ✅
[193/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230712_subsetted.nc4 ✅
[194/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230713_subsetted.nc4 ✅
[195/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230714_subsetted.nc4 ✅
[196/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230715_subsetted.nc4 ✅
[197/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230716_subsetted.nc4 ✅
[198/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230717_subsetted.nc4 ✅
[199/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230718_subsetted.nc4 ✅
[200/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230719_subsetted.nc4 ✅
[201/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230720_subsetted.nc4 ✅
[202/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230721_subsetted.nc4 ✅
[203/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230722_subsetted.nc4 ✅
[204/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230723_subsetted.nc4 ✅
[205/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230724_subsetted.nc4 ✅
[206/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230725_subsetted.nc4 ✅
[207/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230726_subsetted.nc4 ✅
[208/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230727_subsetted.nc4 ✅
[209/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230728_subsetted.nc4 ✅
[210/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230729_subsetted.nc4 ✅
[211/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230730_subsetted.nc4 ✅
[212/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230731_subsetted.nc4 ✅
[213/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230801_subsetted.nc4 ✅
[214/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230802_subsetted.nc4 ✅
[215/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230803_subsetted.nc4 ✅
[216/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230804_subsetted.nc4 ✅
[217/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230805_subsetted.nc4 ✅
[218/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230806_subsetted.nc4 ✅
[219/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230807_subsetted.nc4 ✅
[220/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230808_subsetted.nc4 ✅
[221/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230809_subsetted.nc4 ✅
[222/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230810_subsetted.nc4 ✅
[223/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230811_subsetted.nc4 ✅
[224/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230812_subsetted.nc4 ✅
[225/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230813_subsetted.nc4 ✅
[226/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230814_subsetted.nc4 ✅
[227/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230815_subsetted.nc4 ✅
[228/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230816_subsetted.nc4 ✅
[229/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230817_subsetted.nc4 ✅
[230/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230818_subsetted.nc4 ✅
[231/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230819_subsetted.nc4 ✅
[232/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230820_subsetted.nc4 ✅
[233/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230821_subsetted.nc4 ✅
[234/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230822_subsetted.nc4 ✅
[235/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230823_subsetted.nc4 ✅
[236/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230824_subsetted.nc4 ✅
[237/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230825_subsetted.nc4 ✅
[238/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230826_subsetted.nc4 ✅
[239/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230827_subsetted.nc4 ✅
[240/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230828_subsetted.nc4 ✅
[241/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230829_subsetted.nc4 ✅
[242/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230830_subsetted.nc4 ✅
[243/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230831_subsetted.nc4 ✅
[244/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230901_subsetted.nc4 ✅
[245/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230902_subsetted.nc4 ✅
[246/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230903_subsetted.nc4 ✅
[247/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230904_subsetted.nc4 ✅
[248/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230905_subsetted.nc4 ✅
[249/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230906_subsetted.nc4 ✅
[250/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230907_subsetted.nc4 ✅
[251/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230908_subsetted.nc4 ✅
[252/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230909_subsetted.nc4 ✅
[253/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230910_subsetted.nc4 ✅
[254/730] M2T1NXFLX.5.12.4_MERRA2_400.tavg1_2d_flx_Nx.20230911_subsetted.nc4 ✅

In [4]:
import dask.dataframe as dd
df = dd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\merra_merged.parquet")

In [5]:
# Rows
rows = df.shape[0].compute()

# Columns
cols = df.shape[1]

print("Shape:", (rows, cols))

Shape: (52139520, 10)

In [6]:
df.head()

,datetime,latitude,longitude,PBLH,TLML,QLML,ULML,VLML,SPEED,PRECTOT
0,2023-01-01 00:30:00,6.5,68.125,768.71521,299.251068,0.016384,-3.977004,-3.367228,5.214618,9.699725e-07
1,2023-01-01 00:30:00,6.5,68.750,752.21521,299.204193,0.016086,-3.867629,-3.223185,5.036883,6.440096e-07
2,2023-01-01 00:30:00,6.5,69.375,818.96521,299.297943,0.015598,-3.615676,-3.192423,4.825946,1.596636e-07
3,2023-01-01 00:30:00,6.5,70.000,1035.71521,299.594818,0.014808,-3.277786,-3.235392,4.607196,8.381903e-08
4,2023-01-01 00:30:00,6.5,70.625,1085.71521,299.516693,0.014816,-2.962356,-3.307169,4.443133,8.183997e-08

In [3]:
import pandas as pd

# Load parquet
df = pd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\merra_merged.parquet")

# Convert datetime column
df["datetime"] = pd.to_datetime(df["datetime"])

# Extract date and time
df["date"] = df["datetime"].dt.date
df["time"] = df["datetime"].dt.time

# 1. Unique dates
unique_dates = sorted(df["date"].unique())
print("Unique Dates:")
print(unique_dates)
print("Total Unique Dates:", len(unique_dates))

# 2. Unique time
unique_times = sorted(df["time"].unique())
print("\nUnique Times:")
print(unique_times)
print("Total Unique Times:", len(unique_times))

# 3. Min/Max Latitude
print("\nLatitude Min:", df["latitude"].min())
print("Latitude Max:", df["latitude"].max())

# 4. Min/Max Longitude
print("\nLongitude Min:", df["longitude"].min())
print("Longitude Max:", df["longitude"].max())

Unique Dates:

In [4]:
# Unique lat/lon count
print("\nUnique Latitudes:", df["latitude"].nunique())
print("Unique Longitudes:", df["longitude"].nunique())

# Grid points per timestep
print("\nRows per timestep:")
print(df.groupby("datetime").size().iloc[0])

Unique Latitudes: 62
Unique Longitudes: 48

Rows per timestep:
2976

In [1]:
import pandas as pd

file_path = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\india_clipped\merra_india.parquet"

merra_df = pd.read_parquet(file_path)

# Rows and Columns
print("Rows, Columns:", merra_df.shape)

Rows, Columns: (18904080, 10)

In [3]:
import pandas as pd
import numpy as np

# =========================
# 1. LOAD DATA
# =========================
# Change this to your actual file
merra_df = pd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\india_clipped\merra_india.parquet")
# or:
# merra_df = pd.read_csv("merra_data.csv")

# =========================
# 2. DATETIME FEATURES
# =========================
merra_df['datetime'] = pd.to_datetime(merra_df['datetime'])
merra_df['hour'] = merra_df['datetime'].dt.hour

# =========================
# 3. WIND FEATURES
# =========================
# Wind direction from U and V components
merra_df['wind_dir'] = np.degrees(
    np.arctan2(merra_df['VLML'], merra_df['ULML'])
) % 360

# Keep raw components
merra_df['wind_u'] = merra_df['ULML']
merra_df['wind_v'] = merra_df['VLML']

# =========================
# 4. ATMOSPHERIC FEATURES
# =========================
# Stability / inversion proxy
merra_df['inversion_proxy'] = merra_df['TLML'] / (merra_df['PBLH'] + 1)

# Ventilation coefficient
merra_df['vent_coeff'] = merra_df['PBLH'] * merra_df['SPEED']

# Moisture (specific humidity → g/kg)
merra_df['moisture'] = merra_df['QLML'] * 1000

# =========================
# 5. SAVE PROCESSED DATA
# =========================

# Best option (recommended)
merra_df.to_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\india_clipped\merra_features.parquet", index=False)

# Optional: also save CSV (slower, larger)
# merra_df.to_csv("merra_features.csv", index=False)

print("✅ Feature engineering complete and file saved!")

✅ Feature engineering complete and file saved!

In [2]:
import pandas as pd

file_path = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\merra_daily\merra_daily_grid.parquet"

merra2_df = pd.read_parquet(file_path)

# Rows and Columns
print("Rows, Columns:", merra2_df.shape)

Rows, Columns: (787670, 20)

In [8]:
merra2_df.head()

,lat_round,lon_round,date,PBLH_mean,PBLH_min,PBLH_max,TLML_mean,TLML_max,moisture_mean,moisture_max,SPEED_mean,SPEED_min,PRECTOT_sum,vent_coeff_mean,vent_coeff_min,inversion_proxy_mean,inversion_proxy_max,wind_dir_mean,PBLH_morning_mean,PBLH_morning_min
0,7.5,77.5,2023-01-01,902.368225,693.783630,1093.887451,299.587128,300.549896,15.050393,15.502608,7.057846,5.248474,0.000001,6377.281250,4014.480469,0.337838,0.432336,218.531723,881.254883,859.190308
1,7.5,77.5,2023-01-02,1154.879028,1010.899536,1576.539795,299.099701,299.580170,14.156573,15.285531,8.155637,7.351015,0.000010,9462.201172,7581.365234,0.263144,0.295196,217.744308,1023.768738,1010.899536
2,7.5,77.5,2023-01-03,1233.849487,1011.184998,1668.796509,299.592010,299.903992,13.928544,14.930469,8.150998,7.276108,0.000025,9936.528320,8360.588867,0.251734,0.295884,218.241684,1586.278076,1573.884277
3,7.5,77.5,2023-01-04,1270.916626,1011.202942,1459.748169,299.886688,300.721802,13.815117,14.571502,9.271119,7.918664,0.000013,11807.703125,8885.229492,0.238691,0.295565,221.805923,1040.728271,1011.202942
4,7.5,77.5,2023-01-05,968.733337,688.263245,1455.347778,299.621246,300.677338,15.417347,16.923286,8.129073,6.266124,0.000140,7670.103027,5274.466309,0.328177,0.435424,229.257553,1262.005615,1143.311157

In [5]:
import pyarrow.parquet as pq

file_path = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\merra_daily\merra_daily_grid.parquet"
parquet_file = pq.ParquetFile(file_path)


print("Number of row groups:", parquet_file.num_row_groups)
print("Schema:")
print(parquet_file.schema)

Number of row groups: 1
Schema:
<pyarrow._parquet.ParquetSchema object at 0x000001B46BFAA780>
required group field_id=-1 schema {
  optional double field_id=-1 lat_round;
  optional double field_id=-1 lon_round;
  optional int32 field_id=-1 date (Date);
  optional float field_id=-1 PBLH_mean;
  optional float field_id=-1 PBLH_min;
  optional float field_id=-1 PBLH_max;
  optional float field_id=-1 TLML_mean;
  optional float field_id=-1 TLML_max;
  optional float field_id=-1 moisture_mean;
  optional float field_id=-1 moisture_max;
  optional float field_id=-1 SPEED_mean;
  optional float field_id=-1 SPEED_min;
  optional float field_id=-1 PRECTOT_sum;
  optional float field_id=-1 vent_coeff_mean;
  optional float field_id=-1 vent_coeff_min;
  optional float field_id=-1 inversion_proxy_mean;
  optional float field_id=-1 inversion_proxy_max;
  optional float field_id=-1 wind_dir_mean;
  optional float field_id=-1 PBLH_morning_mean;
  optional float field_id=-1 PBLH_morning_min;
}

In [9]:
min_lat, max_lat = 999, -999
min_lon, max_lon = 999, -999

for i in range(parquet_file.num_row_groups):
    df = parquet_file.read_row_group(i, columns=["lat_round", "lon_round"]).to_pandas()
    
    min_lat = min(min_lat, df["lat_round"].min())
    max_lat = max(max_lat, df["lat_round"].max())
    min_lon = min(min_lon, df["lon_round"].min())
    max_lon = max(max_lon, df["lon_round"].max())

print("Latitude Min:", min_lat)
print("Latitude Max:", max_lat)
print("Longitude Min:", min_lon)
print("Longitude Max:", max_lon)

Latitude Min: 7.5
Latitude Max: 35.5
Longitude Min: 68.12
Longitude Max: 97.5

In [11]:
import pandas as pd

df = pd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\merra_daily\merra_daily_grid.parquet", columns=["date"])

unique_dates = df["date"].drop_duplicates().sort_values()

print(unique_dates)
print("Total unique dates:", len(unique_dates))

0      2023-01-01
1      2023-01-02
2      2023-01-03
3      2023-01-04
4      2023-01-05
          ...
725    2024-12-26
726    2024-12-27
727    2024-12-28
728    2024-12-29
729    2024-12-30
Name: date, Length: 730, dtype: object
Total unique dates: 730

In [1]:
import dask.dataframe as dd

file = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\merra_daily\merra_daily_grid.parquet"

df = dd.read_parquet(file, columns=['lat_round', 'lon_round'])

# Drop duplicates
unique_grids = df.drop_duplicates()

# Count unique pairs
count = unique_grids.shape[0].compute()

print("Unique lat-lon grid points:", count)

Unique lat-lon grid points: 1079