In [1]:
import h5py

file_path = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\raw\insat\Apr26_176936\3RIMG_01FEB2023_0545_L2G_AOD_V02R00.h5"

with h5py.File(file_path, "r") as f:
    # List top-level groups/datasets
    print("Keys:")
    print(list(f.keys()))

Keys:
['AOD', 'latitude', 'longitude', 'time']

In [5]:
def explore(name, obj):
    print(name)
    if isinstance(obj, h5py.Dataset):
        print("  Shape:", obj.shape)
        print("  Dtype:", obj.dtype)
        print()

with h5py.File(file_path, "r") as f:
    f.visititems(explore)

AOD
  Shape: (1, 551, 551)
  Dtype: float32

latitude
  Shape: (551,)
  Dtype: float64

longitude
  Shape: (551,)
  Dtype: float64

time
  Shape: (1,)
  Dtype: float64

In [4]:
with h5py.File(file_path, "r") as f:
    data = f["time"][:]
    print(data[:5])   # first values

[12142425.]

In [6]:
import h5py
import pandas as pd
import numpy as np



with h5py.File(file_path, "r") as f:
    aod = f["AOD"][:]          # (1, 551, 551)
    lat = f["latitude"][:]     # (551,)
    lon = f["longitude"][:]    # (551,)
    time = f["time"][:]        # (1,)

# Take small slice (head)
aod_head = aod[0, :5, :5]   # first 5 lat, first 5 lon

# Create grid for that slice
lat_head = lat[:5]
lon_head = lon[:5]

lat_grid, lon_grid = np.meshgrid(lat_head, lon_head, indexing="ij")

# Make dataframe
head_df = pd.DataFrame({
    "time": time[0],
    "latitude": lat_grid.flatten(),
    "longitude": lon_grid.flatten(),
    "AOD": aod_head.flatten()
})

print(head_df)

          time  latitude  longitude    AOD
0   12142425.0     45.05      45.05 -999.0
1   12142425.0     45.05      45.15 -999.0
2   12142425.0     45.05      45.25 -999.0
3   12142425.0     45.05      45.35 -999.0
4   12142425.0     45.05      45.45 -999.0
5   12142425.0     44.95      45.05 -999.0
6   12142425.0     44.95      45.15 -999.0
7   12142425.0     44.95      45.25 -999.0
8   12142425.0     44.95      45.35 -999.0
9   12142425.0     44.95      45.45 -999.0
10  12142425.0     44.85      45.05 -999.0
11  12142425.0     44.85      45.15 -999.0
12  12142425.0     44.85      45.25 -999.0
13  12142425.0     44.85      45.35 -999.0
14  12142425.0     44.85      45.45 -999.0
15  12142425.0     44.75      45.05 -999.0
16  12142425.0     44.75      45.15 -999.0
17  12142425.0     44.75      45.25 -999.0
18  12142425.0     44.75      45.35 -999.0
19  12142425.0     44.75      45.45 -999.0
20  12142425.0     44.65      45.05 -999.0
21  12142425.0     44.65      45.15 -999.0
22  12142425.0     44.65      45.25 -999.0
23  12142425.0     44.65      45.35 -999.0
24  12142425.0     44.65      45.45 -999.0

In [1]:
import h5py
import numpy as np
import pandas as pd
import os
from glob import glob
import pyarrow as pa
import pyarrow.parquet as pq
from datetime import datetime

# ==============================
# SETTINGS
# ==============================
base_folder = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\raw\insat"
output_file = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\insat_aod_merged.parquet"

LAT_MIN, LAT_MAX = 6, 38
LON_MIN, LON_MAX = 68, 98

# ==============================
# GET ALL H5 FILES
# ==============================
h5_files = glob(os.path.join(base_folder, "**", "*.h5"), recursive=True)
print("Total H5 files:", len(h5_files))

writer = None

# ==============================
# FUNCTION: Extract datetime from filename
# ==============================
def get_datetime_from_filename(file_path):
    filename = os.path.basename(file_path)
    
    # Example: 3RIMG_01FEB2023_0545_L2G_AOD_V02R00.h5
    parts = filename.split("_")
    
    date_str = parts[1]   # 01FEB2023
    time_str = parts[2]   # 0545
    
    dt = datetime.strptime(date_str + time_str, "%d%b%Y%H%M")
    return dt

# ==============================
# PROCESS FILES
# ==============================
for i, file in enumerate(h5_files):
    try:
        with h5py.File(file, "r") as f:
            aod = f["AOD"][:]          
            lat = f["latitude"][:]     
            lon = f["longitude"][:]     

            aod = aod[0]

            # Create grid
            lat_grid, lon_grid = np.meshgrid(lat, lon, indexing="ij")

            # Flatten
            df = pd.DataFrame({
                "latitude": lat_grid.flatten(),
                "longitude": lon_grid.flatten(),
                "AOD": aod.flatten()
            })

            # Filter India
            df = df[
                (df["latitude"] >= LAT_MIN) & (df["latitude"] <= LAT_MAX) &
                (df["longitude"] >= LON_MIN) & (df["longitude"] <= LON_MAX)
            ]

            # Replace missing values
            df["AOD"] = df["AOD"].replace(-999, np.nan)

            # Get datetime from filename
            file_datetime = get_datetime_from_filename(file)
            df["datetime"] = file_datetime

            # Final columns
            df = df[["datetime", "latitude", "longitude", "AOD"]]

            # Convert to parquet table
            table = pa.Table.from_pandas(df)

            # Write incrementally
            if writer is None:
                writer = pq.ParquetWriter(output_file, table.schema)
            
            writer.write_table(table)

            print(f"Processed ({i+1}/{len(h5_files)}):", os.path.basename(file))

    except Exception as e:
        print("Error in:", file)
        print(e)

# Close writer
if writer:
    writer.close()

print("\nFinal file saved as:", output_file)

Total H5 files: 4745
Processed (1/4745): 3RIMG_01FEB2023_0545_L2G_AOD_V02R00.h5
Processed (2/4745): 3RIMG_01FEB2023_0615_L2G_AOD_V02R00.h5
Processed (3/4745): 3RIMG_01FEB2023_0645_L2G_AOD_V02R00.h5
Processed (4/4745): 3RIMG_01FEB2023_0745_L2G_AOD_V02R00.h5
Processed (5/4745): 3RIMG_01FEB2023_0815_L2G_AOD_V02R00.h5
Processed (6/4745): 3RIMG_01FEB2023_0845_L2G_AOD_V02R00.h5
Processed (7/4745): 3RIMG_01JAN2023_0545_L2G_AOD_V02R00.h5
Processed (8/4745): 3RIMG_01JAN2023_0615_L2G_AOD_V02R00.h5
Processed (9/4745): 3RIMG_01JAN2023_0645_L2G_AOD_V02R00.h5
Processed (10/4745): 3RIMG_01JAN2023_0715_L2G_AOD_V02R00.h5
Processed (11/4745): 3RIMG_01JAN2023_0745_L2G_AOD_V02R00.h5
Processed (12/4745): 3RIMG_01JAN2023_0815_L2G_AOD_V02R00.h5
Processed (13/4745): 3RIMG_01JAN2023_0845_L2G_AOD_V02R00.h5
Processed (14/4745): 3RIMG_01MAR2023_0545_L2G_AOD_V02R00.h5
Processed (15/4745): 3RIMG_01MAR2023_0615_L2G_AOD_V02R00.h5
Processed (16/4745): 3RIMG_01MAR2023_0645_L2G_AOD_V02R00.h5
Processed (17/4745): 3RIMG_01MAR2023_0715_L2G_AOD_V02R00.h5
Processed (18/4745): 3RIMG_01MAR2023_0745_L2G_AOD_V02R00.h5
Processed (19/4745): 3RIMG_01MAR2023_0815_L2G_AOD_V02R00.h5
Processed (20/4745): 3RIMG_01MAR2023_0845_L2G_AOD_V02R00.h5
Processed (21/4745): 3RIMG_02FEB2023_0545_L2G_AOD_V02R00.h5
Processed (22/4745): 3RIMG_02FEB2023_0615_L2G_AOD_V02R00.h5
Processed (23/4745): 3RIMG_02FEB2023_0745_L2G_AOD_V02R00.h5
Processed (24/4745): 3RIMG_02FEB2023_0815_L2G_AOD_V02R00.h5
Processed (25/4745): 3RIMG_02FEB2023_0845_L2G_AOD_V02R00.h5
Processed (26/4745): 3RIMG_02JAN2023_0545_L2G_AOD_V02R00.h5
Processed (27/4745): 3RIMG_02JAN2023_0615_L2G_AOD_V02R00.h5
Processed (28/4745): 3RIMG_02JAN2023_0645_L2G_AOD_V02R00.h5
Processed (29/4745): 3RIMG_02JAN2023_0715_L2G_AOD_V02R00.h5
Processed (30/4745): 3RIMG_02JAN2023_0745_L2G_AOD_V02R00.h5
Processed (31/4745): 3RIMG_02JAN2023_0815_L2G_AOD_V02R00.h5
Processed (32/4745): 3RIMG_02JAN2023_0845_L2G_AOD_V02R00.h5
Processed (33/4745): 3RIMG_02MAR2023_0545_L2G_AOD_V02R00.h5
Processed (34/4745): 3RIMG_02MAR2023_0615_L2G_AOD_V02R00.h5
Processed (35/4745): 3RIMG_02MAR2023_0645_L2G_AOD_V02R00.h5
Processed (36/4745): 3RIMG_02MAR2023_0715_L2G_AOD_V02R00.h5
Processed (37/4745): 3RIMG_02MAR2023_0745_L2G_AOD_V02R00.h5
Processed (38/4745): 3RIMG_02MAR2023_0815_L2G_AOD_V02R00.h5
Processed (39/4745): 3RIMG_02MAR2023_0845_L2G_AOD_V02R00.h5
Processed (40/4745): 3RIMG_03FEB2023_0545_L2G_AOD_V02R00.h5
Processed (41/4745): 3RIMG_03FEB2023_0615_L2G_AOD_V02R00.h5
Processed (42/4745): 3RIMG_03FEB2023_0645_L2G_AOD_V02R00.h5
Processed (43/4745): 3RIMG_03FEB2023_0715_L2G_AOD_V02R00.h5
Processed (44/4745): 3RIMG_03FEB2023_0745_L2G_AOD_V02R00.h5
Processed (45/4745): 3RIMG_03FEB2023_0815_L2G_AOD_V02R00.h5
Processed (46/4745): 3RIMG_03FEB2023_0845_L2G_AOD_V02R00.h5
Processed (47/4745): 3RIMG_03JAN2023_0545_L2G_AOD_V02R00.h5
Processed (48/4745): 3RIMG_03JAN2023_0615_L2G_AOD_V02R00.h5
Processed (49/4745): 3RIMG_03JAN2023_0645_L2G_AOD_V02R00.h5
Processed (50/4745): 3RIMG_03JAN2023_0715_L2G_AOD_V02R00.h5
Processed (51/4745): 3RIMG_03JAN2023_0745_L2G_AOD_V02R00.h5
Processed (52/4745): 3RIMG_03JAN2023_0815_L2G_AOD_V02R00.h5
Processed (53/4745): 3RIMG_03JAN2023_0845_L2G_AOD_V02R00.h5
Processed (54/4745): 3RIMG_03MAR2023_0545_L2G_AOD_V02R00.h5
Processed (55/4745): 3RIMG_03MAR2023_0615_L2G_AOD_V02R00.h5
Processed (56/4745): 3RIMG_03MAR2023_0645_L2G_AOD_V02R00.h5
Processed (57/4745): 3RIMG_03MAR2023_0715_L2G_AOD_V02R00.h5
Processed (58/4745): 3RIMG_03MAR2023_0745_L2G_AOD_V02R00.h5
Processed (59/4745): 3RIMG_03MAR2023_0815_L2G_AOD_V02R00.h5
Processed (60/4745): 3RIMG_03MAR2023_0845_L2G_AOD_V02R00.h5
Processed (61/4745): 3RIMG_04FEB2023_0545_L2G_AOD_V02R00.h5
Processed (62/4745): 3RIMG_04FEB2023_0615_L2G_AOD_V02R00.h5
Processed (63/4745): 3RIMG_04FEB2023_0645_L2G_AOD_V02R00.h5
Processed (64/4745): 3RIMG_04FEB2023_0715_L2G_AOD_V02R00.h5
Processed (65/4745): 3RIMG_04FEB2023_0745_L2G_AOD_V02R00.h5
Processed (66/4745): 3RIMG_04FEB2023_0815_L2G_AOD_V02R00.h5
Processed (67/4745): 3RIMG_04FEB2023_0845_L2G_AOD_V02R00.h5
Processed (68/4745): 3RIMG_04JAN2023_0715_L2G_AOD_V02R00.h5
Processed (69/4745): 3RIMG_04JAN2023_0745_L2G_AOD_V02R00.h5
Processed (70/4745): 3RIMG_04JAN2023_0815_L2G_AOD_V02R00.h5
Processed (71/4745): 3RIMG_04JAN2023_0845_L2G_AOD_V02R00.h5
Processed (72/4745): 3RIMG_04MAR2023_0545_L2G_AOD_V02R00.h5
Processed (73/4745): 3RIMG_04MAR2023_0615_L2G_AOD_V02R00.h5
Processed (74/4745): 3RIMG_04MAR2023_0645_L2G_AOD_V02R00.h5
Processed (75/4745): 3RIMG_04MAR2023_0715_L2G_AOD_V02R00.h5
Processed (76/4745): 3RIMG_04MAR2023_0745_L2G_AOD_V02R00.h5
Processed (77/4745): 3RIMG_04MAR2023_0815_L2G_AOD_V02R00.h5
Processed (78/4745): 3RIMG_04MAR2023_0845_L2G_AOD_V02R00.h5
Processed (79/4745): 3RIMG_05FEB2023_0545_L2G_AOD_V02R00.h5
Processed (80/4745): 3RIMG_05FEB2023_0615_L2G_AOD_V02R00.h5
Processed (81/4745): 3RIMG_05FEB2023_0645_L2G_AOD_V02R00.h5
Processed (82/4745): 3RIMG_05FEB2023_0715_L2G_AOD_V02R00.h5
Processed (83/4745): 3RIMG_05FEB2023_0745_L2G_AOD_V02R00.h5
Processed (84/4745): 3RIMG_05FEB2023_0815_L2G_AOD_V02R00.h5
Processed (85/4745): 3RIMG_05FEB2023_0845_L2G_AOD_V02R00.h5
Processed (86/4745): 3RIMG_05JAN2023_0545_L2G_AOD_V02R00.h5
Processed (87/4745): 3RIMG_05JAN2023_0615_L2G_AOD_V02R00.h5
Processed (88/4745): 3RIMG_05JAN2023_0645_L2G_AOD_V02R00.h5
Processed (89/4745): 3RIMG_05JAN2023_0715_L2G_AOD_V02R00.h5
Processed (90/4745): 3RIMG_05JAN2023_0745_L2G_AOD_V02R00.h5
Processed (91/4745): 3RIMG_05JAN2023_0815_L2G_AOD_V02R00.h5
Processed (92/4745): 3RIMG_05JAN2023_0845_L2G_AOD_V02R00.h5
Processed (93/4745): 3RIMG_05MAR2023_0545_L2G_AOD_V02R00.h5
Processed (94/4745): 3RIMG_05MAR2023_0615_L2G_AOD_V02R00.h5
Processed (95/4745): 3RIMG_05MAR2023_0645_L2G_AOD_V02R00.h5
Processed (96/4745): 3RIMG_05MAR2023_0715_L2G_AOD_V02R00.h5
Processed (97/4745): 3RIMG_05MAR2023_0745_L2G_AOD_V02R00.h5
Processed (98/4745): 3RIMG_05MAR2023_0815_L2G_AOD_V02R00.h5
Processed (99/4745): 3RIMG_05MAR2023_0845_L2G_AOD_V02R00.h5
Processed (100/4745): 3RIMG_06FEB2023_0545_L2G_AOD_V02R00.h5
Processed (101/4745): 3RIMG_06FEB2023_0615_L2G_AOD_V02R00.h5
Processed (102/4745): 3RIMG_06FEB2023_0645_L2G_AOD_V02R00.h5
Processed (103/4745): 3RIMG_06FEB2023_0715_L2G_AOD_V02R00.h5
Processed (104/4745): 3RIMG_06FEB2023_0745_L2G_AOD_V02R00.h5
Processed (105/4745): 3RIMG_06FEB2023_0815_L2G_AOD_V02R00.h5
Processed (106/4745): 3RIMG_06FEB2023_0845_L2G_AOD_V02R00.h5
Processed (107/4745): 3RIMG_06JAN2023_0545_L2G_AOD_V02R00.h5
Processed (108/4745): 3RIMG_06JAN2023_0615_L2G_AOD_V02R00.h5
Processed (109/4745): 3RIMG_06JAN2023_0645_L2G_AOD_V02R00.h5
Processed (110/4745): 3RIMG_06JAN2023_0715_L2G_AOD_V02R00.h5
Processed (111/4745): 3RIMG_06JAN2023_0745_L2G_AOD_V02R00.h5
Processed (112/4745): 3RIMG_06JAN2023_0815_L2G_AOD_V02R00.h5
Processed (113/4745): 3RIMG_06JAN2023_0845_L2G_AOD_V02R00.h5
Processed (114/4745): 3RIMG_06MAR2023_0545_L2G_AOD_V02R00.h5
Processed (115/4745): 3RIMG_06MAR2023_0615_L2G_AOD_V02R00.h5
Processed (116/4745): 3RIMG_06MAR2023_0645_L2G_AOD_V02R00.h5
Processed (117/4745): 3RIMG_06MAR2023_0715_L2G_AOD_V02R00.h5
Processed (118/4745): 3RIMG_06MAR2023_0745_L2G_AOD_V02R00.h5
Processed (119/4745): 3RIMG_06MAR2023_0815_L2G_AOD_V02R00.h5
Processed (120/4745): 3RIMG_06MAR2023_0845_L2G_AOD_V02R00.h5
Processed (121/4745): 3RIMG_07FEB2023_0545_L2G_AOD_V02R00.h5
Processed (122/4745): 3RIMG_07FEB2023_0615_L2G_AOD_V02R00.h5
Processed (123/4745): 3RIMG_07FEB2023_0645_L2G_AOD_V02R00.h5
Processed (124/4745): 3RIMG_07FEB2023_0715_L2G_AOD_V02R00.h5
Processed (125/4745): 3RIMG_07FEB2023_0745_L2G_AOD_V02R00.h5
Processed (126/4745): 3RIMG_07FEB2023_0815_L2G_AOD_V02R00.h5
Processed (127/4745): 3RIMG_07FEB2023_0845_L2G_AOD_V02R00.h5
Processed (128/4745): 3RIMG_07JAN2023_0545_L2G_AOD_V02R00.h5
Processed (129/4745): 3RIMG_07JAN2023_0615_L2G_AOD_V02R00.h5
Processed (130/4745): 3RIMG_07JAN2023_0645_L2G_AOD_V02R00.h5
Processed (131/4745): 3RIMG_07JAN2023_0715_L2G_AOD_V02R00.h5
Processed (132/4745): 3RIMG_07JAN2023_0745_L2G_AOD_V02R00.h5
Processed (133/4745): 3RIMG_07JAN2023_0815_L2G_AOD_V02R00.h5
Processed (134/4745): 3RIMG_07JAN2023_0845_L2G_AOD_V02R00.h5
Processed (135/4745): 3RIMG_07MAR2023_0545_L2G_AOD_V02R00.h5
Processed (136/4745): 3RIMG_07MAR2023_0615_L2G_AOD_V02R00.h5
Processed (137/4745): 3RIMG_07MAR2023_0645_L2G_AOD_V02R00.h5
Processed (138/4745): 3RIMG_07MAR2023_0715_L2G_AOD_V02R00.h5
Processed (139/4745): 3RIMG_07MAR2023_0745_L2G_AOD_V02R00.h5
Processed (140/4745): 3RIMG_07MAR2023_0815_L2G_AOD_V02R00.h5
Processed (141/4745): 3RIMG_07MAR2023_0845_L2G_AOD_V02R00.h5
Processed (142/4745): 3RIMG_08FEB2023_0545_L2G_AOD_V02R00.h5
Processed (143/4745): 3RIMG_08FEB2023_0615_L2G_AOD_V02R00.h5
Processed (144/4745): 3RIMG_08FEB2023_0645_L2G_AOD_V02R00.h5
Processed (145/4745): 3RIMG_08FEB2023_0715_L2G_AOD_V02R00.h5
Processed (146/4745): 3RIMG_08FEB2023_0745_L2G_AOD_V02R00.h5
Processed (147/4745): 3RIMG_08FEB2023_0815_L2G_AOD_V02R00.h5
Processed (148/4745): 3RIMG_08FEB2023_0845_L2G_AOD_V02R00.h5
Processed (149/4745): 3RIMG_08JAN2023_0545_L2G_AOD_V02R00.h5
Processed (150/4745): 3RIMG_08JAN2023_0615_L2G_AOD_V02R00.h5
Processed (151/4745): 3RIMG_08JAN2023_0645_L2G_AOD_V02R00.h5
Processed (152/4745): 3RIMG_08JAN2023_0715_L2G_AOD_V02R00.h5
Processed (153/4745): 3RIMG_08JAN2023_0745_L2G_AOD_V02R00.h5
Processed (154/4745): 3RIMG_08JAN2023_0815_L2G_AOD_V02R00.h5
Processed (155/4745): 3RIMG_08JAN2023_0845_L2G_AOD_V02R00.h5
Processed (156/4745): 3RIMG_08MAR2023_0545_L2G_AOD_V02R00.h5
Processed (157/4745): 3RIMG_08MAR2023_0615_L2G_AOD_V02R00.h5
Processed (158/4745): 3RIMG_08MAR2023_0645_L2G_AOD_V02R00.h5
Processed (159/4745): 3RIMG_08MAR2023_0715_L2G_AOD_V02R00.h5
Processed (160/4745): 3RIMG_08MAR2023_0745_L2G_AOD_V02R00.h5
Processed (161/4745): 3RIMG_08MAR2023_0815_L2G_AOD_V02R00.h5
Processed (162/4745): 3RIMG_08MAR2023_0845_L2G_AOD_V02R00.h5
Processed (163/4745): 3RIMG_09FEB2023_0545_L2G_AOD_V02R00.h5
Processed (164/4745): 3RIMG_09FEB2023_0615_L2G_AOD_V02R00.h5
Processed (165/4745): 3RIMG_09FEB2023_0645_L2G_AOD_V02R00.h5
Processed (166/4745): 3RIMG_09FEB2023_0715_L2G_AOD_V02R00.h5
Processed (167/4745): 3RIMG_09FEB2023_0745_L2G_AOD_V02R00.h5
Processed (168/4745): 3RIMG_09FEB2023_0845_L2G_AOD_V02R00.h5
Processed (169/4745): 3RIMG_09JAN2023_0615_L2G_AOD_V02R00.h5
Processed (170/4745): 3RIMG_09JAN2023_0645_L2G_AOD_V02R00.h5
Processed (171/4745): 3RIMG_09JAN2023_0715_L2G_AOD_V02R00.h5
Processed (172/4745): 3RIMG_09JAN2023_0745_L2G_AOD_V02R00.h5
Processed (173/4745): 3RIMG_09JAN2023_0815_L2G_AOD_V02R00.h5
Processed (174/4745): 3RIMG_09JAN2023_0845_L2G_AOD_V02R00.h5
Processed (175/4745): 3RIMG_09MAR2023_0545_L2G_AOD_V02R00.h5
Processed (176/4745): 3RIMG_09MAR2023_0615_L2G_AOD_V02R00.h5
Processed (177/4745): 3RIMG_09MAR2023_0645_L2G_AOD_V02R00.h5
Processed (178/4745): 3RIMG_09MAR2023_0715_L2G_AOD_V02R00.h5
Processed (179/4745): 3RIMG_09MAR2023_0745_L2G_AOD_V02R00.h5
Processed (180/4745): 3RIMG_09MAR2023_0815_L2G_AOD_V02R00.h5
Processed (181/4745): 3RIMG_09MAR2023_0845_L2G_AOD_V02R00.h5
Processed (182/4745): 3RIMG_10FEB2023_0545_L2G_AOD_V02R00.h5
Processed (183/4745): 3RIMG_10FEB2023_0715_L2G_AOD_V02R00.h5
Processed (184/4745): 3RIMG_10FEB2023_0745_L2G_AOD_V02R00.h5
Processed (185/4745): 3RIMG_10FEB2023_0815_L2G_AOD_V02R00.h5
Processed (186/4745): 3RIMG_10FEB2023_0845_L2G_AOD_V02R00.h5
Processed (187/4745): 3RIMG_10JAN2023_0545_L2G_AOD_V02R00.h5
Processed (188/4745): 3RIMG_10JAN2023_0615_L2G_AOD_V02R00.h5
Processed (189/4745): 3RIMG_10JAN2023_0645_L2G_AOD_V02R00.h5
Processed (190/4745): 3RIMG_10JAN2023_0715_L2G_AOD_V02R00.h5
Processed (191/4745): 3RIMG_10JAN2023_0745_L2G_AOD_V02R00.h5
Processed (192/4745): 3RIMG_10JAN2023_0815_L2G_AOD_V02R00.h5
Processed (193/4745): 3RIMG_10JAN2023_0845_L2G_AOD_V02R00.h5
Processed (194/4745): 3RIMG_10MAR2023_0545_L2G_AOD_V02R00.h5
Processed (195/4745): 3RIMG_10MAR2023_0615_L2G_AOD_V02R00.h5
Processed (196/4745): 3RIMG_10MAR2023_0645_L2G_AOD_V02R00.h5
Processed (197/4745): 3RIMG_10MAR2023_0715_L2G_AOD_V02R00.h5
Processed (198/4745): 3RIMG_10MAR2023_0745_L2G_AOD_V02R00.h5
Processed (199/4745): 3RIMG_10MAR2023_0815_L2G_AOD_V02R00.h5
Processed (200/4745): 3RIMG_10MAR2023_0845_L2G_AOD_V02R00.h5
Processed (201/4745): 3RIMG_11FEB2023_0545_L2G_AOD_V02R00.h5
Processed (202/4745): 3RIMG_11FEB2023_0715_L2G_AOD_V02R00.h5
Processed (203/4745): 3RIMG_11FEB2023_0745_L2G_AOD_V02R00.h5
Processed (204/4745): 3RIMG_11FEB2023_0815_L2G_AOD_V02R00.h5
Processed (205/4745): 3RIMG_11FEB2023_0845_L2G_AOD_V02R00.h5
Processed (206/4745): 3RIMG_11JAN2023_0545_L2G_AOD_V02R00.h5
Processed (207/4745): 3RIMG_11JAN2023_0615_L2G_AOD_V02R00.h5
Processed (208/4745): 3RIMG_11JAN2023_0645_L2G_AOD_V02R00.h5
Processed (209/4745): 3RIMG_11JAN2023_0715_L2G_AOD_V02R00.h5
Processed (210/4745): 3RIMG_11JAN2023_0745_L2G_AOD_V02R00.h5
Processed (211/4745): 3RIMG_11JAN2023_0815_L2G_AOD_V02R00.h5
Processed (212/4745): 3RIMG_11JAN2023_0845_L2G_AOD_V02R00.h5
Processed (213/4745): 3RIMG_11MAR2023_0615_L2G_AOD_V02R00.h5
Processed (214/4745): 3RIMG_11MAR2023_0645_L2G_AOD_V02R00.h5
Processed (215/4745): 3RIMG_11MAR2023_0715_L2G_AOD_V02R00.h5
Processed (216/4745): 3RIMG_11MAR2023_0745_L2G_AOD_V02R00.h5
Processed (217/4745): 3RIMG_11MAR2023_0815_L2G_AOD_V02R00.h5
Processed (218/4745): 3RIMG_11MAR2023_0845_L2G_AOD_V02R00.h5
Processed (219/4745): 3RIMG_12FEB2023_0545_L2G_AOD_V02R00.h5
Processed (220/4745): 3RIMG_12FEB2023_0645_L2G_AOD_V02R00.h5
Processed (221/4745): 3RIMG_12FEB2023_0715_L2G_AOD_V02R00.h5
Processed (222/4745): 3RIMG_12FEB2023_0745_L2G_AOD_V02R00.h5
Processed (223/4745): 3RIMG_12FEB2023_0815_L2G_AOD_V02R00.h5
Processed (224/4745): 3RIMG_12FEB2023_0845_L2G_AOD_V02R00.h5
Processed (225/4745): 3RIMG_12JAN2023_0545_L2G_AOD_V02R00.h5
Processed (226/4745): 3RIMG_12JAN2023_0615_L2G_AOD_V02R00.h5
Processed (227/4745): 3RIMG_12JAN2023_0645_L2G_AOD_V02R00.h5
Processed (228/4745): 3RIMG_12JAN2023_0715_L2G_AOD_V02R00.h5
Processed (229/4745): 3RIMG_12JAN2023_0745_L2G_AOD_V02R00.h5
Processed (230/4745): 3RIMG_12JAN2023_0815_L2G_AOD_V02R00.h5
Processed (231/4745): 3RIMG_12JAN2023_0845_L2G_AOD_V02R00.h5
Processed (232/4745): 3RIMG_12MAR2023_0545_L2G_AOD_V02R00.h5
Processed (233/4745): 3RIMG_12MAR2023_0615_L2G_AOD_V02R00.h5
Processed (234/4745): 3RIMG_12MAR2023_0645_L2G_AOD_V02R00.h5
Processed (235/4745): 3RIMG_12MAR2023_0715_L2G_AOD_V02R00.h5
Processed (236/4745): 3RIMG_12MAR2023_0745_L2G_AOD_V02R00.h5
Processed (237/4745): 3RIMG_12MAR2023_0815_L2G_AOD_V02R00.h5
Processed (238/4745): 3RIMG_12MAR2023_0845_L2G_AOD_V02R00.h5
Processed (239/4745): 3RIMG_13FEB2023_0545_L2G_AOD_V02R00.h5
Processed (240/4745): 3RIMG_13FEB2023_0645_L2G_AOD_V02R00.h5
Processed (241/4745): 3RIMG_13FEB2023_0715_L2G_AOD_V02R00.h5
Processed (242/4745): 3RIMG_13FEB2023_0745_L2G_AOD_V02R00.h5
Processed (243/4745): 3RIMG_13FEB2023_0815_L2G_AOD_V02R00.h5
Processed (244/4745): 3RIMG_13FEB2023_0845_L2G_AOD_V02R00.h5
Processed (245/4745): 3RIMG_13JAN2023_0545_L2G_AOD_V02R00.h5
Processed (246/4745): 3RIMG_13JAN2023_0615_L2G_AOD_V02R00.h5
Processed (247/4745): 3RIMG_13JAN2023_0645_L2G_AOD_V02R00.h5
Processed (248/4745): 3RIMG_13JAN2023_0715_L2G_AOD_V02R00.h5
Processed (249/4745): 3RIMG_13JAN2023_0745_L2G_AOD_V02R00.h5
Processed (250/4745): 3RIMG_13JAN2023_0815_L2G_AOD_V02R00.h5
Processed (251/4745): 3RIMG_13JAN2023_0845_L2G_AOD_V02R00.h5
Processed (252/4745): 3RIMG_13MAR2023_0645_L2G_AOD_V02R00.h5
Processed (253/4745): 3RIMG_13MAR2023_0715_L2G_AOD_V02R00.h5
Processed (254/4745): 3RIMG_13MAR2023_0745_L2G_AOD_V02R00.h5
Processed (255/4745): 3RIMG_13MAR2023_0815_L2G_AOD_V02R00.h5
Processed (256/4745): 3RIMG_13MAR2023_0845_L2G_AOD_V02R00.h5
Processed (257/4745): 3RIMG_14FEB2023_0545_L2G_AOD_V02R00.h5
Processed (258/4745): 3RIMG_14FEB2023_0615_L2G_AOD_V02R00.h5
Processed (259/4745): 3RIMG_14FEB2023_0645_L2G_AOD_V02R00.h5
Processed (260/4745): 3RIMG_14FEB2023_0715_L2G_AOD_V02R00.h5
Processed (261/4745): 3RIMG_14FEB2023_0745_L2G_AOD_V02R00.h5
Processed (262/4745): 3RIMG_14FEB2023_0815_L2G_AOD_V02R00.h5
Processed (263/4745): 3RIMG_14FEB2023_0845_L2G_AOD_V02R00.h5
Processed (264/4745): 3RIMG_14JAN2023_0545_L2G_AOD_V02R00.h5
Processed (265/4745): 3RIMG_14JAN2023_0615_L2G_AOD_V02R00.h5
Processed (266/4745): 3RIMG_14JAN2023_0645_L2G_AOD_V02R00.h5
Processed (267/4745): 3RIMG_14JAN2023_0715_L2G_AOD_V02R00.h5
Processed (268/4745): 3RIMG_14JAN2023_0745_L2G_AOD_V02R00.h5
Processed (269/4745): 3RIMG_14JAN2023_0815_L2G_AOD_V02R00.h5
Processed (270/4745): 3RIMG_14JAN2023_0845_L2G_AOD_V02R00.h5
Processed (271/4745): 3RIMG_14MAR2023_0545_L2G_AOD_V02R00.h5
Processed (272/4745): 3RIMG_14MAR2023_0615_L2G_AOD_V02R00.h5
Processed (273/4745): 3RIMG_14MAR2023_0645_L2G_AOD_V02R00.h5
Processed (274/4745): 3RIMG_14MAR2023_0715_L2G_AOD_V02R00.h5
Processed (275/4745): 3RIMG_14MAR2023_0815_L2G_AOD_V02R00.h5
Processed (276/4745): 3RIMG_14MAR2023_0845_L2G_AOD_V02R00.h5
Processed (277/4745): 3RIMG_15FEB2023_0545_L2G_AOD_V02R00.h5
Processed (278/4745): 3RIMG_15FEB2023_0645_L2G_AOD_V02R00.h5
Processed (279/4745): 3RIMG_15FEB2023_0715_L2G_AOD_V02R00.h5
Processed (280/4745): 3RIMG_15FEB2023_0815_L2G_AOD_V02R00.h5
Processed (281/4745): 3RIMG_15FEB2023_0845_L2G_AOD_V02R00.h5
Processed (282/4745): 3RIMG_15JAN2023_0545_L2G_AOD_V02R00.h5
Processed (283/4745): 3RIMG_15JAN2023_0615_L2G_AOD_V02R00.h5
Processed (284/4745): 3RIMG_15JAN2023_0645_L2G_AOD_V02R00.h5
Processed (285/4745): 3RIMG_15JAN2023_0715_L2G_AOD_V02R00.h5
Processed (286/4745): 3RIMG_15JAN2023_0745_L2G_AOD_V02R00.h5
Processed (287/4745): 3RIMG_15JAN2023_0815_L2G_AOD_V02R00.h5
Processed (288/4745): 3RIMG_15JAN2023_0845_L2G_AOD_V02R00.h5
Processed (289/4745): 3RIMG_15MAR2023_0545_L2G_AOD_V02R00.h5
Processed (290/4745): 3RIMG_15MAR2023_0615_L2G_AOD_V02R00.h5
Processed (291/4745): 3RIMG_15MAR2023_0645_L2G_AOD_V02R00.h5
Processed (292/4745): 3RIMG_15MAR2023_0715_L2G_AOD_V02R00.h5
Processed (293/4745): 3RIMG_15MAR2023_0745_L2G_AOD_V02R00.h5
Processed (294/4745): 3RIMG_15MAR2023_0815_L2G_AOD_V02R00.h5
Processed (295/4745): 3RIMG_15MAR2023_0845_L2G_AOD_V02R00.h5
Processed (296/4745): 3RIMG_16FEB2023_0545_L2G_AOD_V02R00.h5
Processed (297/4745): 3RIMG_16FEB2023_0645_L2G_AOD_V02R00.h5
Processed (298/4745): 3RIMG_16FEB2023_0715_L2G_AOD_V02R00.h5
Processed (299/4745): 3RIMG_16FEB2023_0745_L2G_AOD_V02R00.h5
Processed (300/4745): 3RIMG_16FEB2023_0815_L2G_AOD_V02R00.h5
Processed (301/4745): 3RIMG_16JAN2023_0545_L2G_AOD_V02R00.h5
Processed (302/4745): 3RIMG_16JAN2023_0615_L2G_AOD_V02R00.h5
Processed (303/4745): 3RIMG_16JAN2023_0645_L2G_AOD_V02R00.h5
Processed (304/4745): 3RIMG_16JAN2023_0715_L2G_AOD_V02R00.h5
Processed (305/4745): 3RIMG_16JAN2023_0745_L2G_AOD_V02R00.h5
Processed (306/4745): 3RIMG_16JAN2023_0815_L2G_AOD_V02R00.h5
Processed (307/4745): 3RIMG_16JAN2023_0845_L2G_AOD_V02R00.h5
Processed (308/4745): 3RIMG_16MAR2023_0545_L2G_AOD_V02R00.h5
Processed (309/4745): 3RIMG_16MAR2023_0615_L2G_AOD_V02R00.h5
Processed (310/4745): 3RIMG_16MAR2023_0645_L2G_AOD_V02R00.h5
Processed (311/4745): 3RIMG_16MAR2023_0715_L2G_AOD_V02R00.h5
Processed (312/4745): 3RIMG_16MAR2023_0745_L2G_AOD_V02R00.h5
Processed (313/4745): 3RIMG_16MAR2023_0845_L2G_AOD_V02R00.h5
Processed (314/4745): 3RIMG_17FEB2023_0645_L2G_AOD_V02R00.h5
Processed (315/4745): 3RIMG_17FEB2023_0715_L2G_AOD_V02R00.h5
Processed (316/4745): 3RIMG_17FEB2023_0745_L2G_AOD_V02R00.h5
Processed (317/4745): 3RIMG_17FEB2023_0815_L2G_AOD_V02R00.h5
Processed (318/4745): 3RIMG_17FEB2023_0845_L2G_AOD_V02R00.h5
Processed (319/4745): 3RIMG_17JAN2023_0545_L2G_AOD_V02R00.h5
Processed (320/4745): 3RIMG_17JAN2023_0615_L2G_AOD_V02R00.h5
Processed (321/4745): 3RIMG_17JAN2023_0645_L2G_AOD_V02R00.h5
Processed (322/4745): 3RIMG_17JAN2023_0715_L2G_AOD_V02R00.h5
Processed (323/4745): 3RIMG_17JAN2023_0745_L2G_AOD_V02R00.h5
Processed (324/4745): 3RIMG_17JAN2023_0845_L2G_AOD_V02R00.h5
Processed (325/4745): 3RIMG_17MAR2023_0545_L2G_AOD_V02R00.h5
Processed (326/4745): 3RIMG_17MAR2023_0615_L2G_AOD_V02R00.h5
Processed (327/4745): 3RIMG_17MAR2023_0645_L2G_AOD_V02R00.h5
Processed (328/4745): 3RIMG_17MAR2023_0715_L2G_AOD_V02R00.h5
Processed (329/4745): 3RIMG_17MAR2023_0745_L2G_AOD_V02R00.h5

In [2]:
import pyarrow.parquet as pq

file_path = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\insat_aod_merged.parquet"

parquet_file = pq.ParquetFile(file_path)

print("Row groups:", parquet_file.num_row_groups)

# Read ONLY first row group (safe)
table = parquet_file.read_row_group(0)

df_sample = table.to_pandas()

print(df_sample.head())

Row groups: 4745
                 datetime  latitude  longitude  AOD
39351 2023-02-01 05:45:00     37.95      68.05  NaN
39352 2023-02-01 05:45:00     37.95      68.15  NaN
39353 2023-02-01 05:45:00     37.95      68.25  NaN
39354 2023-02-01 05:45:00     37.95      68.35  NaN
39355 2023-02-01 05:45:00     37.95      68.45  NaN

In [3]:
import pyarrow.parquet as pq

file = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\insat_aod_merged.parquet"
parquet_file = pq.ParquetFile(file)

print("Number of row groups:", parquet_file.num_row_groups)
print("Schema:")
print(parquet_file.schema)

Number of row groups: 4745
Schema:
<pyarrow._parquet.ParquetSchema object at 0x000002B8100E0580>
required group field_id=-1 schema {
  optional int64 field_id=-1 datetime (Timestamp(isAdjustedToUTC=false, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false));
  optional double field_id=-1 latitude;
  optional double field_id=-1 longitude;
  optional float field_id=-1 AOD;
  optional int64 field_id=-1 __index_level_0__;
}

In [4]:
import os

# File size
size_mb = os.path.getsize(file) / (1024 * 1024)
print("File size (MB):", round(size_mb, 2))

# Total rows
total_rows = parquet_file.metadata.num_rows
print("Total rows:", total_rows)

File size (MB): 3293.39
Total rows: 455520000

In [5]:
import pandas as pd

unique_dates = set()

for i in range(parquet_file.num_row_groups):
    df = parquet_file.read_row_group(i, columns=["datetime"]).to_pandas()
    unique_dates.update(df["datetime"].dt.date.unique())

print("Unique Dates:")
print(sorted(unique_dates))
print("Total Unique Dates:", len(unique_dates))

Unique Dates:
[datetime.date(2023, 1, 1), datetime.date(2023, 1, 2), datetime.date(2023, 1, 3), datetime.date(2023, 1, 4), datetime.date(2023, 1, 5), datetime.date(2023, 1, 6), datetime.date(2023, 1, 7), datetime.date(2023, 1, 8), datetime.date(2023, 1, 9), datetime.date(2023, 1, 10), datetime.date(2023, 1, 11), datetime.date(2023, 1, 12), datetime.date(2023, 1, 13), datetime.date(2023, 1, 14), datetime.date(2023, 1, 15), datetime.date(2023, 1, 16), datetime.date(2023, 1, 17), datetime.date(2023, 1, 18), datetime.date(2023, 1, 19), datetime.date(2023, 1, 20), datetime.date(2023, 1, 21), datetime.date(2023, 1, 22), datetime.date(2023, 1, 23), datetime.date(2023, 1, 24), datetime.date(2023, 1, 25), datetime.date(2023, 1, 26), datetime.date(2023, 1, 27), datetime.date(2023, 1, 28), datetime.date(2023, 1, 29), datetime.date(2023, 1, 30), datetime.date(2023, 1, 31), datetime.date(2023, 2, 1), datetime.date(2023, 2, 2), datetime.date(2023, 2, 3), datetime.date(2023, 2, 4), datetime.date(2023, 2, 5), datetime.date(2023, 2, 6), datetime.date(2023, 2, 7), datetime.date(2023, 2, 8), datetime.date(2023, 2, 9), datetime.date(2023, 2, 10), datetime.date(2023, 2, 11), datetime.date(2023, 2, 12), datetime.date(2023, 2, 13), datetime.date(2023, 2, 14), datetime.date(2023, 2, 15), datetime.date(2023, 2, 16), datetime.date(2023, 2, 17), datetime.date(2023, 2, 18), datetime.date(2023, 2, 19), datetime.date(2023, 2, 20), datetime.date(2023, 2, 21), datetime.date(2023, 2, 22), datetime.date(2023, 2, 23), datetime.date(2023, 2, 24), datetime.date(2023, 2, 25), datetime.date(2023, 2, 26), datetime.date(2023, 2, 27), datetime.date(2023, 2, 28), datetime.date(2023, 3, 1), datetime.date(2023, 3, 2), datetime.date(2023, 3, 3), datetime.date(2023, 3, 4), datetime.date(2023, 3, 5), datetime.date(2023, 3, 6), datetime.date(2023, 3, 7), datetime.date(2023, 3, 8), datetime.date(2023, 3, 9), datetime.date(2023, 3, 10), datetime.date(2023, 3, 11), datetime.date(2023, 3, 12), datetime.date(2023, 3, 13), datetime.date(2023, 3, 14), datetime.date(2023, 3, 15), datetime.date(2023, 3, 16), datetime.date(2023, 3, 17), datetime.date(2023, 3, 18), datetime.date(2023, 3, 19), datetime.date(2023, 3, 20), datetime.date(2023, 3, 21), datetime.date(2023, 3, 22), datetime.date(2023, 3, 23), datetime.date(2023, 3, 24), datetime.date(2023, 3, 25), datetime.date(2023, 3, 26), datetime.date(2023, 3, 27), datetime.date(2023, 3, 28), datetime.date(2023, 3, 29), datetime.date(2023, 3, 30), datetime.date(2023, 3, 31), datetime.date(2023, 4, 1), datetime.date(2023, 4, 2), datetime.date(2023, 4, 3), datetime.date(2023, 4, 4), datetime.date(2023, 4, 5), datetime.date(2023, 4, 6), datetime.date(2023, 4, 7), datetime.date(2023, 4, 8), datetime.date(2023, 4, 9), datetime.date(2023, 4, 10), datetime.date(2023, 4, 11), datetime.date(2023, 4, 12), datetime.date(2023, 4, 13), datetime.date(2023, 4, 14), datetime.date(2023, 4, 15), datetime.date(2023, 4, 16), datetime.date(2023, 4, 17), datetime.date(2023, 4, 18), datetime.date(2023, 4, 19), datetime.date(2023, 4, 20), datetime.date(2023, 4, 21), datetime.date(2023, 4, 22), datetime.date(2023, 4, 23), datetime.date(2023, 4, 24), datetime.date(2023, 4, 25), datetime.date(2023, 4, 26), datetime.date(2023, 4, 27), datetime.date(2023, 4, 28), datetime.date(2023, 4, 29), datetime.date(2023, 4, 30), datetime.date(2023, 5, 1), datetime.date(2023, 5, 2), datetime.date(2023, 5, 3), datetime.date(2023, 5, 4), datetime.date(2023, 5, 5), datetime.date(2023, 5, 6), datetime.date(2023, 5, 7), datetime.date(2023, 5, 8), datetime.date(2023, 5, 15), datetime.date(2023, 5, 16), datetime.date(2023, 5, 17), datetime.date(2023, 5, 18), datetime.date(2023, 5, 19), datetime.date(2023, 5, 20), datetime.date(2023, 5, 21), datetime.date(2023, 5, 22), datetime.date(2023, 5, 23), datetime.date(2023, 5, 24), datetime.date(2023, 5, 25), datetime.date(2023, 5, 26), datetime.date(2023, 5, 27), datetime.date(2023, 5, 28), datetime.date(2023, 5, 29), datetime.date(2023, 5, 30), datetime.date(2023, 5, 31), datetime.date(2023, 6, 1), datetime.date(2023, 6, 2), datetime.date(2023, 6, 3), datetime.date(2023, 6, 4), datetime.date(2023, 6, 5), datetime.date(2023, 6, 6), datetime.date(2023, 6, 16), datetime.date(2023, 6, 17), datetime.date(2023, 6, 18), datetime.date(2023, 6, 19), datetime.date(2023, 6, 20), datetime.date(2023, 6, 21), datetime.date(2023, 6, 22), datetime.date(2023, 6, 23), datetime.date(2023, 6, 24), datetime.date(2023, 6, 25), datetime.date(2023, 6, 26), datetime.date(2023, 6, 27), datetime.date(2023, 6, 28), datetime.date(2023, 6, 29), datetime.date(2023, 6, 30), datetime.date(2023, 7, 1), datetime.date(2023, 7, 2), datetime.date(2023, 7, 3), datetime.date(2023, 7, 4), datetime.date(2023, 7, 5), datetime.date(2023, 7, 6), datetime.date(2023, 7, 7), datetime.date(2023, 7, 8), datetime.date(2023, 7, 9), datetime.date(2023, 7, 10), datetime.date(2023, 7, 11), datetime.date(2023, 7, 12), datetime.date(2023, 7, 13), datetime.date(2023, 7, 14), datetime.date(2023, 7, 15), datetime.date(2023, 7, 16), datetime.date(2023, 7, 17), datetime.date(2023, 7, 18), datetime.date(2023, 7, 19), datetime.date(2023, 7, 20), datetime.date(2023, 7, 21), datetime.date(2023, 7, 22), datetime.date(2023, 7, 23), datetime.date(2023, 7, 24), datetime.date(2023, 7, 25), datetime.date(2023, 7, 26), datetime.date(2023, 7, 27), datetime.date(2023, 7, 28), datetime.date(2023, 7, 29), datetime.date(2023, 7, 30), datetime.date(2023, 7, 31), datetime.date(2023, 8, 1), datetime.date(2023, 8, 2), datetime.date(2023, 8, 3), datetime.date(2023, 8, 4), datetime.date(2023, 8, 5), datetime.date(2023, 8, 6), datetime.date(2023, 8, 7), datetime.date(2023, 8, 8), datetime.date(2023, 8, 9), datetime.date(2023, 8, 10), datetime.date(2023, 8, 11), datetime.date(2023, 8, 12), datetime.date(2023, 8, 13), datetime.date(2023, 8, 14), datetime.date(2023, 8, 15), datetime.date(2023, 8, 16), datetime.date(2023, 8, 17), datetime.date(2023, 8, 18), datetime.date(2023, 8, 19), datetime.date(2023, 8, 20), datetime.date(2023, 8, 21), datetime.date(2023, 8, 22), datetime.date(2023, 8, 23), datetime.date(2023, 8, 24), datetime.date(2023, 8, 25), datetime.date(2023, 8, 26), datetime.date(2023, 8, 27), datetime.date(2023, 8, 28), datetime.date(2023, 8, 29), datetime.date(2023, 8, 30), datetime.date(2023, 8, 31), datetime.date(2023, 9, 1), datetime.date(2023, 9, 2), datetime.date(2023, 9, 3), datetime.date(2023, 9, 4), datetime.date(2023, 9, 5), datetime.date(2023, 9, 6), datetime.date(2023, 9, 7), datetime.date(2023, 9, 8), datetime.date(2023, 9, 9), datetime.date(2023, 9, 10), datetime.date(2023, 9, 11), datetime.date(2023, 9, 12), datetime.date(2023, 9, 13), datetime.date(2023, 9, 14), datetime.date(2023, 9, 15), datetime.date(2023, 9, 16), datetime.date(2023, 9, 17), datetime.date(2023, 9, 18), datetime.date(2023, 9, 19), datetime.date(2023, 9, 20), datetime.date(2023, 9, 21), datetime.date(2023, 9, 22), datetime.date(2023, 9, 23), datetime.date(2023, 9, 24), datetime.date(2023, 9, 25), datetime.date(2023, 9, 26), datetime.date(2023, 9, 27), datetime.date(2023, 9, 28), datetime.date(2023, 9, 29), datetime.date(2023, 9, 30), datetime.date(2023, 10, 1), datetime.date(2023, 10, 2), datetime.date(2023, 10, 3), datetime.date(2023, 10, 4), datetime.date(2023, 10, 5), datetime.date(2023, 10, 6), datetime.date(2023, 10, 7), datetime.date(2023, 10, 8), datetime.date(2023, 10, 9), datetime.date(2023, 10, 10), datetime.date(2023, 10, 11), datetime.date(2023, 10, 12), datetime.date(2023, 10, 13), datetime.date(2023, 10, 14), datetime.date(2023, 10, 15), datetime.date(2023, 10, 16), datetime.date(2023, 10, 17), datetime.date(2023, 10, 18), datetime.date(2023, 10, 19), datetime.date(2023, 10, 20), datetime.date(2023, 10, 21), datetime.date(2023, 10, 25), datetime.date(2023, 10, 26), datetime.date(2023, 10, 27), datetime.date(2023, 10, 28), datetime.date(2023, 10, 29), datetime.date(2023, 10, 30), datetime.date(2023, 10, 31), datetime.date(2023, 11, 1), datetime.date(2023, 11, 2), datetime.date(2023, 11, 3), datetime.date(2023, 11, 4), datetime.date(2023, 11, 5), datetime.date(2023, 11, 6), datetime.date(2023, 11, 7), datetime.date(2023, 11, 8), datetime.date(2023, 11, 9), datetime.date(2023, 11, 10), datetime.date(2023, 11, 11), datetime.date(2023, 11, 12), datetime.date(2023, 11, 13), datetime.date(2023, 11, 14), datetime.date(2023, 11, 15), datetime.date(2023, 11, 16), datetime.date(2023, 11, 17), datetime.date(2023, 11, 18), datetime.date(2023, 11, 19), datetime.date(2023, 11, 20), datetime.date(2023, 11, 21), datetime.date(2023, 11, 22), datetime.date(2023, 11, 23), datetime.date(2023, 11, 24), datetime.date(2023, 11, 25), datetime.date(2023, 11, 26), datetime.date(2023, 11, 27), datetime.date(2023, 11, 28), datetime.date(2023, 11, 29), datetime.date(2023, 11, 30), datetime.date(2023, 12, 1), datetime.date(2023, 12, 2), datetime.date(2023, 12, 6), datetime.date(2023, 12, 7), datetime.date(2023, 12, 8), datetime.date(2023, 12, 9), datetime.date(2023, 12, 10), datetime.date(2023, 12, 11), datetime.date(2023, 12, 12), datetime.date(2023, 12, 13), datetime.date(2023, 12, 14), datetime.date(2023, 12, 15), datetime.date(2023, 12, 16), datetime.date(2023, 12, 17), datetime.date(2023, 12, 18), datetime.date(2023, 12, 19), datetime.date(2023, 12, 20), datetime.date(2023, 12, 21), datetime.date(2023, 12, 22), datetime.date(2023, 12, 23), datetime.date(2023, 12, 24), datetime.date(2023, 12, 25), datetime.date(2023, 12, 26), datetime.date(2023, 12, 27), datetime.date(2023, 12, 28), datetime.date(2023, 12, 29), datetime.date(2023, 12, 30), datetime.date(2023, 12, 31), datetime.date(2024, 1, 1), datetime.date(2024, 1, 2), datetime.date(2024, 1, 3), datetime.date(2024, 1, 4), datetime.date(2024, 1, 5), datetime.date(2024, 1, 6), datetime.date(2024, 1, 7), datetime.date(2024, 1, 8), datetime.date(2024, 1, 9), datetime.date(2024, 1, 10), datetime.date(2024, 1, 11), datetime.date(2024, 1, 12), datetime.date(2024, 1, 13), datetime.date(2024, 1, 14), datetime.date(2024, 1, 15), datetime.date(2024, 1, 16), datetime.date(2024, 1, 17), datetime.date(2024, 1, 18), datetime.date(2024, 1, 19), datetime.date(2024, 1, 20), datetime.date(2024, 1, 21), datetime.date(2024, 1, 22), datetime.date(2024, 1, 23), datetime.date(2024, 1, 24), datetime.date(2024, 1, 25), datetime.date(2024, 1, 26), datetime.date(2024, 1, 27), datetime.date(2024, 1, 28), datetime.date(2024, 1, 29), datetime.date(2024, 1, 30), datetime.date(2024, 1, 31), datetime.date(2024, 2, 1), datetime.date(2024, 2, 2), datetime.date(2024, 2, 3), datetime.date(2024, 2, 4), datetime.date(2024, 2, 5), datetime.date(2024, 2, 6), datetime.date(2024, 2, 7), datetime.date(2024, 2, 8), datetime.date(2024, 2, 9), datetime.date(2024, 2, 10), datetime.date(2024, 2, 11), datetime.date(2024, 2, 12), datetime.date(2024, 2, 13), datetime.date(2024, 2, 14), datetime.date(2024, 2, 15), datetime.date(2024, 2, 16), datetime.date(2024, 2, 17), datetime.date(2024, 2, 18), datetime.date(2024, 2, 19), datetime.date(2024, 2, 20), datetime.date(2024, 2, 21), datetime.date(2024, 2, 22), datetime.date(2024, 2, 23), datetime.date(2024, 2, 24), datetime.date(2024, 2, 25), datetime.date(2024, 2, 26), datetime.date(2024, 2, 27), datetime.date(2024, 2, 28), datetime.date(2024, 2, 29), datetime.date(2024, 3, 1), datetime.date(2024, 3, 2), datetime.date(2024, 3, 3), datetime.date(2024, 3, 4), datetime.date(2024, 3, 5), datetime.date(2024, 3, 6), datetime.date(2024, 3, 7), datetime.date(2024, 3, 8), datetime.date(2024, 3, 9), datetime.date(2024, 3, 10), datetime.date(2024, 3, 11), datetime.date(2024, 3, 12), datetime.date(2024, 3, 13), datetime.date(2024, 3, 14), datetime.date(2024, 3, 15), datetime.date(2024, 3, 16), datetime.date(2024, 3, 17), datetime.date(2024, 3, 18), datetime.date(2024, 3, 19), datetime.date(2024, 3, 20), datetime.date(2024, 3, 21), datetime.date(2024, 3, 22), datetime.date(2024, 3, 23), datetime.date(2024, 3, 24), datetime.date(2024, 3, 25), datetime.date(2024, 3, 26), datetime.date(2024, 3, 27), datetime.date(2024, 3, 28), datetime.date(2024, 3, 29), datetime.date(2024, 3, 30), datetime.date(2024, 3, 31), datetime.date(2024, 4, 1), datetime.date(2024, 4, 2), datetime.date(2024, 4, 3), datetime.date(2024, 4, 4), datetime.date(2024, 4, 5), datetime.date(2024, 4, 6), datetime.date(2024, 4, 7), datetime.date(2024, 4, 8), datetime.date(2024, 4, 9), datetime.date(2024, 4, 10), datetime.date(2024, 4, 11), datetime.date(2024, 4, 12), datetime.date(2024, 4, 13), datetime.date(2024, 4, 14), datetime.date(2024, 4, 15), datetime.date(2024, 4, 16), datetime.date(2024, 4, 17), datetime.date(2024, 4, 18), datetime.date(2024, 4, 19), datetime.date(2024, 4, 20), datetime.date(2024, 4, 21), datetime.date(2024, 4, 22), datetime.date(2024, 4, 23), datetime.date(2024, 4, 24), datetime.date(2024, 4, 25), datetime.date(2024, 4, 26), datetime.date(2024, 4, 27), datetime.date(2024, 4, 28), datetime.date(2024, 4, 29), datetime.date(2024, 4, 30), datetime.date(2024, 5, 1), datetime.date(2024, 5, 2), datetime.date(2024, 5, 3), datetime.date(2024, 5, 4), datetime.date(2024, 5, 5), datetime.date(2024, 5, 6), datetime.date(2024, 5, 7), datetime.date(2024, 5, 8), datetime.date(2024, 5, 9), datetime.date(2024, 5, 10), datetime.date(2024, 5, 11), datetime.date(2024, 5, 12), datetime.date(2024, 5, 13), datetime.date(2024, 5, 14), datetime.date(2024, 5, 15), datetime.date(2024, 5, 16), datetime.date(2024, 5, 17), datetime.date(2024, 5, 18), datetime.date(2024, 5, 19), datetime.date(2024, 5, 20), datetime.date(2024, 5, 21), datetime.date(2024, 5, 22), datetime.date(2024, 5, 23), datetime.date(2024, 5, 24), datetime.date(2024, 5, 25), datetime.date(2024, 5, 28), datetime.date(2024, 5, 29), datetime.date(2024, 5, 30), datetime.date(2024, 5, 31), datetime.date(2024, 6, 1), datetime.date(2024, 6, 2), datetime.date(2024, 6, 3), datetime.date(2024, 6, 4), datetime.date(2024, 6, 5), datetime.date(2024, 6, 6), datetime.date(2024, 6, 7), datetime.date(2024, 6, 8), datetime.date(2024, 6, 9), datetime.date(2024, 6, 10), datetime.date(2024, 6, 12), datetime.date(2024, 6, 13), datetime.date(2024, 6, 14), datetime.date(2024, 6, 15), datetime.date(2024, 6, 16), datetime.date(2024, 6, 17), datetime.date(2024, 6, 18), datetime.date(2024, 6, 19), datetime.date(2024, 6, 20), datetime.date(2024, 6, 21), datetime.date(2024, 6, 22), datetime.date(2024, 6, 23), datetime.date(2024, 6, 24), datetime.date(2024, 6, 25), datetime.date(2024, 6, 26), datetime.date(2024, 6, 27), datetime.date(2024, 6, 28), datetime.date(2024, 6, 29), datetime.date(2024, 6, 30), datetime.date(2024, 7, 1), datetime.date(2024, 7, 2), datetime.date(2024, 7, 3), datetime.date(2024, 7, 4), datetime.date(2024, 7, 5), datetime.date(2024, 7, 6), datetime.date(2024, 7, 7), datetime.date(2024, 7, 8), datetime.date(2024, 7, 9), datetime.date(2024, 7, 10), datetime.date(2024, 7, 11), datetime.date(2024, 7, 12), datetime.date(2024, 7, 13), datetime.date(2024, 7, 14), datetime.date(2024, 7, 15), datetime.date(2024, 7, 16), datetime.date(2024, 7, 17), datetime.date(2024, 7, 18), datetime.date(2024, 7, 19), datetime.date(2024, 7, 20), datetime.date(2024, 7, 21), datetime.date(2024, 7, 22), datetime.date(2024, 7, 23), datetime.date(2024, 7, 24), datetime.date(2024, 7, 25), datetime.date(2024, 7, 26), datetime.date(2024, 7, 27), datetime.date(2024, 7, 28), datetime.date(2024, 7, 29), datetime.date(2024, 7, 30), datetime.date(2024, 7, 31), datetime.date(2024, 8, 1), datetime.date(2024, 8, 2), datetime.date(2024, 8, 3), datetime.date(2024, 8, 4), datetime.date(2024, 8, 5), datetime.date(2024, 8, 6), datetime.date(2024, 8, 7), datetime.date(2024, 8, 8), datetime.date(2024, 8, 9), datetime.date(2024, 8, 10), datetime.date(2024, 8, 11), datetime.date(2024, 8, 12), datetime.date(2024, 8, 13), datetime.date(2024, 8, 14), datetime.date(2024, 8, 15), datetime.date(2024, 8, 16), datetime.date(2024, 8, 17), datetime.date(2024, 8, 18), datetime.date(2024, 8, 19), datetime.date(2024, 8, 20), datetime.date(2024, 8, 21), datetime.date(2024, 8, 22), datetime.date(2024, 8, 23), datetime.date(2024, 8, 24), datetime.date(2024, 8, 25), datetime.date(2024, 8, 26), datetime.date(2024, 8, 27), datetime.date(2024, 8, 28), datetime.date(2024, 8, 29), datetime.date(2024, 8, 30), datetime.date(2024, 8, 31), datetime.date(2024, 9, 1), datetime.date(2024, 9, 2), datetime.date(2024, 9, 3), datetime.date(2024, 9, 4), datetime.date(2024, 9, 5), datetime.date(2024, 9, 6), datetime.date(2024, 9, 7), datetime.date(2024, 9, 8), datetime.date(2024, 9, 9), datetime.date(2024, 9, 10), datetime.date(2024, 9, 11), datetime.date(2024, 9, 12), datetime.date(2024, 9, 13), datetime.date(2024, 9, 14), datetime.date(2024, 9, 15), datetime.date(2024, 9, 16), datetime.date(2024, 9, 17), datetime.date(2024, 9, 18), datetime.date(2024, 9, 19), datetime.date(2024, 9, 20), datetime.date(2024, 9, 21), datetime.date(2024, 9, 22), datetime.date(2024, 9, 23), datetime.date(2024, 9, 24), datetime.date(2024, 9, 25), datetime.date(2024, 9, 26), datetime.date(2024, 9, 27), datetime.date(2024, 9, 28), datetime.date(2024, 9, 29), datetime.date(2024, 9, 30), datetime.date(2024, 10, 1), datetime.date(2024, 10, 2), datetime.date(2024, 10, 3), datetime.date(2024, 10, 4), datetime.date(2024, 10, 5), datetime.date(2024, 10, 6), datetime.date(2024, 10, 7), datetime.date(2024, 10, 8), datetime.date(2024, 10, 9), datetime.date(2024, 10, 10), datetime.date(2024, 10, 11), datetime.date(2024, 10, 12), datetime.date(2024, 10, 13), datetime.date(2024, 10, 14), datetime.date(2024, 10, 15), datetime.date(2024, 10, 16), datetime.date(2024, 10, 17), datetime.date(2024, 10, 18), datetime.date(2024, 10, 19), datetime.date(2024, 10, 20), datetime.date(2024, 10, 21), datetime.date(2024, 10, 22), datetime.date(2024, 10, 23), datetime.date(2024, 10, 24), datetime.date(2024, 10, 25), datetime.date(2024, 10, 26), datetime.date(2024, 10, 27), datetime.date(2024, 10, 28), datetime.date(2024, 10, 29), datetime.date(2024, 10, 30), datetime.date(2024, 10, 31), datetime.date(2024, 11, 1), datetime.date(2024, 11, 2), datetime.date(2024, 11, 3), datetime.date(2024, 11, 4), datetime.date(2024, 11, 5), datetime.date(2024, 11, 6), datetime.date(2024, 11, 7), datetime.date(2024, 11, 8), datetime.date(2024, 11, 9), datetime.date(2024, 11, 10), datetime.date(2024, 11, 11), datetime.date(2024, 11, 12), datetime.date(2024, 11, 13), datetime.date(2024, 11, 14), datetime.date(2024, 11, 15), datetime.date(2024, 11, 16), datetime.date(2024, 11, 17), datetime.date(2024, 11, 18), datetime.date(2024, 11, 19), datetime.date(2024, 11, 20), datetime.date(2024, 11, 21), datetime.date(2024, 11, 22), datetime.date(2024, 11, 23), datetime.date(2024, 11, 24), datetime.date(2024, 11, 25), datetime.date(2024, 11, 26), datetime.date(2024, 11, 27), datetime.date(2024, 11, 28), datetime.date(2024, 11, 29), datetime.date(2024, 11, 30), datetime.date(2024, 12, 1), datetime.date(2024, 12, 2), datetime.date(2024, 12, 3), datetime.date(2024, 12, 4), datetime.date(2024, 12, 5), datetime.date(2024, 12, 6), datetime.date(2024, 12, 7), datetime.date(2024, 12, 8), datetime.date(2024, 12, 9), datetime.date(2024, 12, 10), datetime.date(2024, 12, 11), datetime.date(2024, 12, 12), datetime.date(2024, 12, 13), datetime.date(2024, 12, 14), datetime.date(2024, 12, 15), datetime.date(2024, 12, 16), datetime.date(2024, 12, 17), datetime.date(2024, 12, 18), datetime.date(2024, 12, 19), datetime.date(2024, 12, 20), datetime.date(2024, 12, 21), datetime.date(2024, 12, 22), datetime.date(2024, 12, 23), datetime.date(2024, 12, 24), datetime.date(2024, 12, 25), datetime.date(2024, 12, 26), datetime.date(2024, 12, 27), datetime.date(2024, 12, 28), datetime.date(2024, 12, 29), datetime.date(2024, 12, 30), datetime.date(2024, 12, 31)]
Total Unique Dates: 707

In [6]:
unique_times = set()

for i in range(parquet_file.num_row_groups):
    df = parquet_file.read_row_group(i, columns=["datetime"]).to_pandas()
    unique_times.update(df["datetime"].dt.time.unique())

print("Unique Times:")
print(sorted(unique_times))
print("Total Unique Times:", len(unique_times))

Unique Times:
[datetime.time(5, 45), datetime.time(6, 15), datetime.time(6, 45), datetime.time(7, 15), datetime.time(7, 45), datetime.time(8, 15), datetime.time(8, 45)]
Total Unique Times: 7

In [7]:
min_lat, max_lat = 999, -999
min_lon, max_lon = 999, -999

for i in range(parquet_file.num_row_groups):
    df = parquet_file.read_row_group(i, columns=["latitude", "longitude"]).to_pandas()
    
    min_lat = min(min_lat, df["latitude"].min())
    max_lat = max(max_lat, df["latitude"].max())
    min_lon = min(min_lon, df["longitude"].min())
    max_lon = max(max_lon, df["longitude"].max())

print("Latitude Min:", min_lat)
print("Latitude Max:", max_lat)
print("Longitude Min:", min_lon)
print("Longitude Max:", max_lon)

Latitude Min: 6.049999999999997
Latitude Max: 37.949999999999996
Longitude Min: 68.05
Longitude Max: 97.95

In [8]:
null_count = 0
total_count = 0

for i in range(parquet_file.num_row_groups):
    df = parquet_file.read_row_group(i, columns=["AOD"]).to_pandas()
    
    null_count += df["AOD"].isna().sum()
    total_count += len(df)

print("Total rows:", total_count)
print("Null AOD rows:", null_count)
print("Null %:", (null_count / total_count) * 100)

Total rows: 455520000
Null AOD rows: 335204568
Null %: 73.58723393045311

In [9]:
rows_per_time = {}

for i in range(parquet_file.num_row_groups):
    df = parquet_file.read_row_group(i, columns=["datetime"]).to_pandas()
    counts = df["datetime"].value_counts()
    
    for k, v in counts.items():
        rows_per_time[k] = v

print("Sample rows per timestamp:")
print(list(rows_per_time.items())[:5])

Sample rows per timestamp:
[(Timestamp('2023-02-01 05:45:00'), 96000), (Timestamp('2023-02-01 06:15:00'), 96000), (Timestamp('2023-02-01 06:45:00'), 96000), (Timestamp('2023-02-01 07:45:00'), 96000), (Timestamp('2023-02-01 08:15:00'), 96000)]

In [11]:
import pandas as pd

file_path = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\india_clipped\insat_india.parquet"

insat_df = pd.read_parquet(file_path)

# Rows and Columns
print("Rows, Columns:", insat_df.shape)

insat_df['datetime'] = pd.to_datetime(insat_df['datetime'])
insat_df['hour'] = insat_df['datetime'].dt.hour
insat_df['month'] = insat_df['datetime'].dt.month

missing_by_hour = insat_df.groupby('hour')['AOD'].apply(
    lambda x: x.isna().mean() * 100
)

print(missing_by_hour)

Rows, Columns: (160812795, 4)
hour
5    64.345413
6    69.358687
7    68.814755
8    63.528856
Name: AOD, dtype: float64

In [12]:
import pyarrow.parquet as pq
import pyarrow as pa
import pandas as pd
import os

input_file = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\india_clipped\insat_india.parquet"
output_file = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\india_clipped\insat_india_clean.parquet"

os.makedirs(os.path.dirname(output_file), exist_ok=True)

pf = pq.ParquetFile(input_file)
writer = None
total_rows = 0
kept_rows = 0

for i in range(pf.num_row_groups):
    print(f"Processing row group {i+1}/{pf.num_row_groups}")
    
    df = pf.read_row_group(i).to_pandas()
    
    # Convert datetime
    df["datetime"] = pd.to_datetime(df["datetime"])
    
    # Extract hour
    df["hour"] = df["datetime"].dt.hour
    
    # Rule 1 — Keep daytime AOD only
    df = df[df["hour"].between(5, 14)]
    
    # Rule 2 — Drop NaN AOD
    df = df.dropna(subset=["AOD"])
    
    # Rule 3 — Physical AOD range
    df = df[(df["AOD"] >= 0.1) & (df["AOD"] <= 3.0)]
    
    df = df.drop(columns=["hour"])
    
    total_rows += pf.metadata.row_group(i).num_rows
    kept_rows += len(df)
    
    if len(df) == 0:
        continue

    table = pa.Table.from_pandas(df)

    if writer is None:
        writer = pq.ParquetWriter(output_file, table.schema)

    writer.write_table(table)

if writer:
    writer.close()

print("\nOriginal rows:", total_rows)
print("Retained rows:", kept_rows)
print("Retention %:", (kept_rows / total_rows) * 100)
print("Saved to:", output_file)

Processing row group 1/4745
Processing row group 2/4745
Processing row group 3/4745
Processing row group 4/4745
Processing row group 5/4745
Processing row group 6/4745
Processing row group 7/4745
Processing row group 8/4745
Processing row group 9/4745
Processing row group 10/4745
Processing row group 11/4745
Processing row group 12/4745
Processing row group 13/4745
Processing row group 14/4745
Processing row group 15/4745
Processing row group 16/4745
Processing row group 17/4745
Processing row group 18/4745
Processing row group 19/4745
Processing row group 20/4745
Processing row group 21/4745
Processing row group 22/4745
Processing row group 23/4745
Processing row group 24/4745
Processing row group 25/4745
Processing row group 26/4745
Processing row group 27/4745
Processing row group 28/4745
Processing row group 29/4745
Processing row group 30/4745
Processing row group 31/4745
Processing row group 32/4745
Processing row group 33/4745
Processing row group 34/4745
Processing row group 35/4745
Processing row group 36/4745
Processing row group 37/4745
Processing row group 38/4745
Processing row group 39/4745
Processing row group 40/4745
Processing row group 41/4745
Processing row group 42/4745
Processing row group 43/4745
Processing row group 44/4745
Processing row group 45/4745
Processing row group 46/4745
Processing row group 47/4745
Processing row group 48/4745
Processing row group 49/4745
Processing row group 50/4745
Processing row group 51/4745
Processing row group 52/4745
Processing row group 53/4745
Processing row group 54/4745
Processing row group 55/4745
Processing row group 56/4745
Processing row group 57/4745
Processing row group 58/4745
Processing row group 59/4745
Processing row group 60/4745
Processing row group 61/4745
Processing row group 62/4745
Processing row group 63/4745
Processing row group 64/4745
Processing row group 65/4745
Processing row group 66/4745
Processing row group 67/4745
Processing row group 68/4745
Processing row group 69/4745
Processing row group 70/4745
Processing row group 71/4745
Processing row group 72/4745
Processing row group 73/4745
Processing row group 74/4745
Processing row group 75/4745
Processing row group 76/4745
Processing row group 77/4745
Processing row group 78/4745
Processing row group 79/4745
Processing row group 80/4745
Processing row group 81/4745
Processing row group 82/4745
Processing row group 83/4745
Processing row group 84/4745
Processing row group 85/4745
Processing row group 86/4745
Processing row group 87/4745
Processing row group 88/4745
Processing row group 89/4745
Processing row group 90/4745
Processing row group 91/4745
Processing row group 92/4745
Processing row group 93/4745
Processing row group 94/4745
Processing row group 95/4745
Processing row group 96/4745
Processing row group 97/4745
Processing row group 98/4745
Processing row group 99/4745
Processing row group 100/4745
Processing row group 101/4745
Processing row group 102/4745
Processing row group 103/4745
Processing row group 104/4745
Processing row group 105/4745
Processing row group 106/4745
Processing row group 107/4745
Processing row group 108/4745
Processing row group 109/4745
Processing row group 110/4745
Processing row group 111/4745
Processing row group 112/4745
Processing row group 113/4745
Processing row group 114/4745
Processing row group 115/4745
Processing row group 116/4745
Processing row group 117/4745
Processing row group 118/4745
Processing row group 119/4745
Processing row group 120/4745
Processing row group 121/4745
Processing row group 122/4745
Processing row group 123/4745
Processing row group 124/4745
Processing row group 125/4745
Processing row group 126/4745
Processing row group 127/4745
Processing row group 128/4745
Processing row group 129/4745
Processing row group 130/4745
Processing row group 131/4745
Processing row group 132/4745
Processing row group 133/4745
Processing row group 134/4745
Processing row group 135/4745
Processing row group 136/4745
Processing row group 137/4745
Processing row group 138/4745
Processing row group 139/4745
Processing row group 140/4745
Processing row group 141/4745
Processing row group 142/4745
Processing row group 143/4745
Processing row group 144/4745
Processing row group 145/4745
Processing row group 146/4745
Processing row group 147/4745
Processing row group 148/4745
Processing row group 149/4745
Processing row group 150/4745
Processing row group 151/4745
Processing row group 152/4745
Processing row group 153/4745
Processing row group 154/4745
Processing row group 155/4745
Processing row group 156/4745
Processing row group 157/4745
Processing row group 158/4745
Processing row group 159/4745
Processing row group 160/4745
Processing row group 161/4745
Processing row group 162/4745
Processing row group 163/4745
Processing row group 164/4745
Processing row group 165/4745
Processing row group 166/4745
Processing row group 167/4745
Processing row group 168/4745
Processing row group 169/4745
Processing row group 170/4745
Processing row group 171/4745
Processing row group 172/4745
Processing row group 173/4745
Processing row group 174/4745
Processing row group 175/4745
Processing row group 176/4745
Processing row group 177/4745
Processing row group 178/4745
Processing row group 179/4745
Processing row group 180/4745
Processing row group 181/4745
Processing row group 182/4745
Processing row group 183/4745
Processing row group 184/4745
Processing row group 185/4745
Processing row group 186/4745
Processing row group 187/4745
Processing row group 188/4745
Processing row group 189/4745
Processing row group 190/4745
Processing row group 191/4745
Processing row group 192/4745
Processing row group 193/4745
Processing row group 194/4745
Processing row group 195/4745
Processing row group 196/4745
Processing row group 197/4745
Processing row group 198/4745
Processing row group 199/4745
Processing row group 200/4745
Processing row group 201/4745
Processing row group 202/4745
Processing row group 203/4745
Processing row group 204/4745
Processing row group 205/4745
Processing row group 206/4745
Processing row group 207/4745
Processing row group 208/4745
Processing row group 209/4745
Processing row group 210/4745
Processing row group 211/4745
Processing row group 212/4745
Processing row group 213/4745
Processing row group 214/4745
Processing row group 215/4745
Processing row group 216/4745
Processing row group 217/4745
Processing row group 218/4745
Processing row group 219/4745
Processing row group 220/4745
Processing row group 221/4745
Processing row group 222/4745
Processing row group 223/4745
Processing row group 224/4745
Processing row group 225/4745
Processing row group 226/4745
Processing row group 227/4745
Processing row group 228/4745
Processing row group 229/4745
Processing row group 230/4745
Processing row group 231/4745
Processing row group 232/4745
Processing row group 233/4745
Processing row group 234/4745
Processing row group 235/4745
Processing row group 236/4745
Processing row group 237/4745
Processing row group 238/4745
Processing row group 239/4745
Processing row group 240/4745
Processing row group 241/4745
Processing row group 242/4745
Processing row group 243/4745
Processing row group 244/4745
Processing row group 245/4745
Processing row group 246/4745
Processing row group 247/4745
Processing row group 248/4745
Processing row group 249/4745
Processing row group 250/4745
Processing row group 251/4745
Processing row group 252/4745
Processing row group 253/4745
Processing row group 254/4745
Processing row group 255/4745
Processing row group 256/4745
Processing row group 257/4745
Processing row group 258/4745
Processing row group 259/4745
Processing row group 260/4745
Processing row group 261/4745
Processing row group 262/4745
Processing row group 263/4745
Processing row group 264/4745
Processing row group 265/4745
Processing row group 266/4745
Processing row group 267/4745
Processing row group 268/4745
Processing row group 269/4745
Processing row group 270/4745
Processing row group 271/4745
Processing row group 272/4745
Processing row group 273/4745
Processing row group 274/4745
Processing row group 275/4745
Processing row group 276/4745
Processing row group 277/4745
Processing row group 278/4745
Processing row group 279/4745
Processing row group 280/4745
Processing row group 281/4745
Processing row group 282/4745
Processing row group 283/4745
Processing row group 284/4745
Processing row group 285/4745
Processing row group 286/4745
Processing row group 287/4745
Processing row group 288/4745
Processing row group 289/4745
Processing row group 290/4745
Processing row group 291/4745
Processing row group 292/4745
Processing row group 293/4745
Processing row group 294/4745
Processing row group 295/4745
Processing row group 296/4745
Processing row group 297/4745
Processing row group 298/4745
Processing row group 299/4745
Processing row group 300/4745
Processing row group 301/4745
Processing row group 302/4745
Processing row group 303/4745
Processing row group 304/4745
Processing row group 305/4745
Processing row group 306/4745
Processing row group 307/4745
Processing row group 308/4745
Processing row group 309/4745
Processing row group 310/4745
Processing row group 311/4745
Processing row group 312/4745
Processing row group 313/4745
Processing row group 314/4745
Processing row group 315/4745
Processing row group 316/4745
Processing row group 317/4745
Processing row group 318/4745
Processing row group 319/4745
Processing row group 320/4745
Processing row group 321/4745
Processing row group 322/4745
Processing row group 323/4745
Processing row group 324/4745
Processing row group 325/4745
Processing row group 326/4745
Processing row group 327/4745
Processing row group 328/4745
Processing row group 329/4745
Processing row group 330/4745
Processing row group 331/4745
Processing row group 332/4745
Processing row group 333/4745
Processing row group 334/4745
Processing row group 335/4745
Processing row group 336/4745
Processing row group 337/4745
Processing row group 338/4745
Processing row group 339/4745
Processing row group 340/4745
Processing row group 341/4745
Processing row group 342/4745
Processing row group 343/4745
Processing row group 344/4745
Processing row group 345/4745
Processing row group 346/4745
Processing row group 347/4745
Processing row group 348/4745
Processing row group 349/4745
Processing row group 350/4745
Processing row group 351/4745
Processing row group 352/4745
Processing row group 353/4745
Processing row group 354/4745
Processing row group 355/4745
Processing row group 356/4745
Processing row group 357/4745
Processing row group 358/4745
Processing row group 359/4745
Processing row group 360/4745
Processing row group 361/4745
Processing row group 362/4745
Processing row group 363/4745
Processing row group 364/4745
Processing row group 365/4745
Processing row group 366/4745
Processing row group 367/4745
Processing row group 368/4745
Processing row group 369/4745
Processing row group 370/4745
Processing row group 371/4745
Processing row group 372/4745
Processing row group 373/4745
Processing row group 374/4745
Processing row group 375/4745
Processing row group 376/4745
Processing row group 377/4745
Processing row group 378/4745
Processing row group 379/4745
Processing row group 380/4745
Processing row group 381/4745
Processing row group 382/4745
Processing row group 383/4745
Processing row group 384/4745
Processing row group 385/4745
Processing row group 386/4745
Processing row group 387/4745
Processing row group 388/4745
Processing row group 389/4745
Processing row group 390/4745
Processing row group 391/4745
Processing row group 392/4745
Processing row group 393/4745
Processing row group 394/4745
Processing row group 395/4745
Processing row group 396/4745
Processing row group 397/4745
Processing row group 398/4745
Processing row group 399/4745
Processing row group 400/4745
Processing row group 401/4745
Processing row group 402/4745
Processing row group 403/4745
Processing row group 404/4745
Processing row group 405/4745
Processing row group 406/4745
Processing row group 407/4745
Processing row group 408/4745
Processing row group 409/4745
Processing row group 410/4745
Processing row group 411/4745
Processing row group 412/4745
Processing row group 413/4745
Processing row group 414/4745
Processing row group 415/4745
Processing row group 416/4745
Processing row group 417/4745
Processing row group 418/4745
Processing row group 419/4745
Processing row group 420/4745
Processing row group 421/4745
Processing row group 422/4745
Processing row group 423/4745
Processing row group 424/4745
Processing row group 425/4745
Processing row group 426/4745
Processing row group 427/4745
Processing row group 428/4745
Processing row group 429/4745
Processing row group 430/4745
Processing row group 431/4745
Processing row group 432/4745
Processing row group 433/4745
Processing row group 434/4745
Processing row group 435/4745
Processing row group 436/4745
Processing row group 437/4745
Processing row group 438/4745
Processing row group 439/4745
Processing row group 440/4745
Processing row group 441/4745
Processing row group 442/4745
Processing row group 443/4745
Processing row group 444/4745
Processing row group 445/4745
Processing row group 446/4745
Processing row group 447/4745
Processing row group 448/4745
Processing row group 449/4745
Processing row group 450/4745
Processing row group 451/4745
Processing row group 452/4745
Processing row group 453/4745
Processing row group 454/4745
Processing row group 455/4745
Processing row group 456/4745
Processing row group 457/4745
Processing row group 458/4745
Processing row group 459/4745
Processing row group 460/4745
Processing row group 461/4745
Processing row group 462/4745
Processing row group 463/4745
Processing row group 464/4745
Processing row group 465/4745
Processing row group 466/4745
Processing row group 467/4745
Processing row group 468/4745
Processing row group 469/4745
Processing row group 470/4745
Processing row group 471/4745
Processing row group 472/4745
Processing row group 473/4745
Processing row group 474/4745
Processing row group 475/4745
Processing row group 476/4745
Processing row group 477/4745
Processing row group 478/4745
Processing row group 479/4745
Processing row group 480/4745
Processing row group 481/4745
Processing row group 482/4745
Processing row group 483/4745
Processing row group 484/4745
Processing row group 485/4745
Processing row group 486/4745
Processing row group 487/4745
Processing row group 488/4745
Processing row group 489/4745
Processing row group 490/4745
Processing row group 491/4745
Processing row group 492/4745
Processing row group 493/4745
Processing row group 494/4745
Processing row group 495/4745
Processing row group 496/4745
Processing row group 497/4745
Processing row group 498/4745
Processing row group 499/4745
Processing row group 500/4745
Processing row group 501/4745
Processing row group 502/4745
Processing row group 503/4745
Processing row group 504/4745
Processing row group 505/4745
Processing row group 506/4745
Processing row group 507/4745
Processing row group 508/4745
Processing row group 509/4745
Processing row group 510/4745
Processing row group 511/4745
Processing row group 512/4745
Processing row group 513/4745
Processing row group 514/4745
Processing row group 515/4745
Processing row group 516/4745
Processing row group 517/4745
Processing row group 518/4745
Processing row group 519/4745
Processing row group 520/4745
Processing row group 521/4745
Processing row group 522/4745
Processing row group 523/4745
Processing row group 524/4745
Processing row group 525/4745
Processing row group 526/4745
Processing row group 527/4745
Processing row group 528/4745
Processing row group 529/4745
Processing row group 530/4745
Processing row group 531/4745
Processing row group 532/4745
Processing row group 533/4745
Processing row group 534/4745
Processing row group 535/4745
Processing row group 536/4745
Processing row group 537/4745
Processing row group 538/4745
Processing row group 539/4745
Processing row group 540/4745
Processing row group 541/4745
Processing row group 542/4745
Processing row group 543/4745
Processing row group 544/4745
Processing row group 545/4745
Processing row group 546/4745
Processing row group 547/4745
Processing row group 548/4745
Processing row group 549/4745
Processing row group 550/4745
Processing row group 551/4745
Processing row group 552/4745
Processing row group 553/4745
Processing row group 554/4745
Processing row group 555/4745
Processing row group 556/4745
Processing row group 557/4745
Processing row group 558/4745
Processing row group 559/4745
Processing row group 560/4745
Processing row group 561/4745
Processing row group 562/4745
Processing row group 563/4745
Processing row group 564/4745
Processing row group 565/4745
Processing row group 566/4745
Processing row group 567/4745
Processing row group 568/4745
Processing row group 569/4745
Processing row group 570/4745
Processing row group 571/4745
Processing row group 572/4745
Processing row group 573/4745
Processing row group 574/4745
Processing row group 575/4745
Processing row group 576/4745
Processing row group 577/4745
Processing row group 578/4745
Processing row group 579/4745
Processing row group 580/4745
Processing row group 581/4745
Processing row group 582/4745
Processing row group 583/4745
Processing row group 584/4745
Processing row group 585/4745
Processing row group 586/4745
Processing row group 587/4745
Processing row group 588/4745
Processing row group 589/4745
Processing row group 590/4745
Processing row group 591/4745
Processing row group 592/4745
Processing row group 593/4745
Processing row group 594/4745
Processing row group 595/4745
Processing row group 596/4745
Processing row group 597/4745
Processing row group 598/4745
Processing row group 599/4745
Processing row group 600/4745
Processing row group 601/4745
Processing row group 602/4745
Processing row group 603/4745
Processing row group 604/4745
Processing row group 605/4745
Processing row group 606/4745
Processing row group 607/4745
Processing row group 608/4745
Processing row group 609/4745
Processing row group 610/4745
Processing row group 611/4745
Processing row group 612/4745
Processing row group 613/4745
Processing row group 614/4745
Processing row group 615/4745
Processing row group 616/4745
Processing row group 617/4745
Processing row group 618/4745
Processing row group 619/4745
Processing row group 620/4745
Processing row group 621/4745
Processing row group 622/4745
Processing row group 623/4745
Processing row group 624/4745
Processing row group 625/4745
Processing row group 626/4745
Processing row group 627/4745
Processing row group 628/4745
Processing row group 629/4745
Processing row group 630/4745
Processing row group 631/4745
Processing row group 632/4745
Processing row group 633/4745
Processing row group 634/4745
Processing row group 635/4745
Processing row group 636/4745
Processing row group 637/4745
Processing row group 638/4745
Processing row group 639/4745
Processing row group 640/4745
Processing row group 641/4745
Processing row group 642/4745
Processing row group 643/4745
Processing row group 644/4745
Processing row group 645/4745
Processing row group 646/4745
Processing row group 647/4745
Processing row group 648/4745
Processing row group 649/4745
Processing row group 650/4745
Processing row group 651/4745
Processing row group 652/4745
Processing row group 653/4745
Processing row group 654/4745
Processing row group 655/4745
Processing row group 656/4745
Processing row group 657/4745
Processing row group 658/4745
Processing row group 659/4745
Processing row group 660/4745
Processing row group 661/4745
Processing row group 662/4745
Processing row group 663/4745
Processing row group 664/4745
Processing row group 665/4745
Processing row group 666/4745
Processing row group 667/4745
Processing row group 668/4745
Processing row group 669/4745
Processing row group 670/4745

In [13]:
import pandas as pd

file_path = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\india_clipped\insat_india_clean.parquet"

merra2_df = pd.read_parquet(file_path)

# Rows and Columns
print("Rows, Columns:", merra2_df.shape)

Rows, Columns: (51360120, 4)

In [15]:
import pyarrow.parquet as pq

file_path = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\india_clipped\insat_india_clean.parquet"
parquet_file = pq.ParquetFile(file_path)


print("Number of row groups:", parquet_file.num_row_groups)
print("Schema:")
print(parquet_file.schema)

Number of row groups: 4745
Schema:
<pyarrow._parquet.ParquetSchema object at 0x000002B85577D340>
required group field_id=-1 schema {
  optional int64 field_id=-1 datetime (Timestamp(isAdjustedToUTC=false, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false));
  optional double field_id=-1 latitude;
  optional double field_id=-1 longitude;
  optional float field_id=-1 AOD;
  optional int64 field_id=-1 __index_level_0__;
}

In [16]:
import pandas as pd

unique_dates = set()

for i in range(parquet_file.num_row_groups):
    df = parquet_file.read_row_group(i, columns=["datetime"]).to_pandas()
    unique_dates.update(df["datetime"].dt.date.unique())

print("Unique Dates:")
print(sorted(unique_dates))
print("Total Unique Dates:", len(unique_dates))

Unique Dates:
[datetime.date(2023, 1, 1), datetime.date(2023, 1, 2), datetime.date(2023, 1, 3), datetime.date(2023, 1, 4), datetime.date(2023, 1, 5), datetime.date(2023, 1, 6), datetime.date(2023, 1, 7), datetime.date(2023, 1, 8), datetime.date(2023, 1, 9), datetime.date(2023, 1, 10), datetime.date(2023, 1, 11), datetime.date(2023, 1, 12), datetime.date(2023, 1, 13), datetime.date(2023, 1, 14), datetime.date(2023, 1, 15), datetime.date(2023, 1, 16), datetime.date(2023, 1, 17), datetime.date(2023, 1, 18), datetime.date(2023, 1, 19), datetime.date(2023, 1, 20), datetime.date(2023, 1, 21), datetime.date(2023, 1, 22), datetime.date(2023, 1, 23), datetime.date(2023, 1, 24), datetime.date(2023, 1, 25), datetime.date(2023, 1, 26), datetime.date(2023, 1, 27), datetime.date(2023, 1, 28), datetime.date(2023, 1, 29), datetime.date(2023, 1, 30), datetime.date(2023, 1, 31), datetime.date(2023, 2, 1), datetime.date(2023, 2, 2), datetime.date(2023, 2, 3), datetime.date(2023, 2, 4), datetime.date(2023, 2, 5), datetime.date(2023, 2, 6), datetime.date(2023, 2, 7), datetime.date(2023, 2, 8), datetime.date(2023, 2, 9), datetime.date(2023, 2, 10), datetime.date(2023, 2, 11), datetime.date(2023, 2, 12), datetime.date(2023, 2, 13), datetime.date(2023, 2, 14), datetime.date(2023, 2, 15), datetime.date(2023, 2, 16), datetime.date(2023, 2, 17), datetime.date(2023, 2, 18), datetime.date(2023, 2, 19), datetime.date(2023, 2, 20), datetime.date(2023, 2, 21), datetime.date(2023, 2, 22), datetime.date(2023, 2, 23), datetime.date(2023, 2, 24), datetime.date(2023, 2, 25), datetime.date(2023, 2, 26), datetime.date(2023, 2, 27), datetime.date(2023, 2, 28), datetime.date(2023, 3, 1), datetime.date(2023, 3, 2), datetime.date(2023, 3, 3), datetime.date(2023, 3, 4), datetime.date(2023, 3, 5), datetime.date(2023, 3, 6), datetime.date(2023, 3, 7), datetime.date(2023, 3, 8), datetime.date(2023, 3, 9), datetime.date(2023, 3, 10), datetime.date(2023, 3, 11), datetime.date(2023, 3, 12), datetime.date(2023, 3, 13), datetime.date(2023, 3, 14), datetime.date(2023, 3, 15), datetime.date(2023, 3, 16), datetime.date(2023, 3, 17), datetime.date(2023, 3, 18), datetime.date(2023, 3, 19), datetime.date(2023, 3, 20), datetime.date(2023, 3, 21), datetime.date(2023, 3, 22), datetime.date(2023, 3, 23), datetime.date(2023, 3, 24), datetime.date(2023, 3, 25), datetime.date(2023, 3, 26), datetime.date(2023, 3, 27), datetime.date(2023, 3, 28), datetime.date(2023, 3, 29), datetime.date(2023, 3, 30), datetime.date(2023, 3, 31), datetime.date(2023, 4, 1), datetime.date(2023, 4, 2), datetime.date(2023, 4, 3), datetime.date(2023, 4, 4), datetime.date(2023, 4, 5), datetime.date(2023, 4, 6), datetime.date(2023, 4, 7), datetime.date(2023, 4, 8), datetime.date(2023, 4, 9), datetime.date(2023, 4, 10), datetime.date(2023, 4, 11), datetime.date(2023, 4, 12), datetime.date(2023, 4, 13), datetime.date(2023, 4, 14), datetime.date(2023, 4, 15), datetime.date(2023, 4, 16), datetime.date(2023, 4, 17), datetime.date(2023, 4, 18), datetime.date(2023, 4, 19), datetime.date(2023, 4, 20), datetime.date(2023, 4, 21), datetime.date(2023, 4, 22), datetime.date(2023, 4, 23), datetime.date(2023, 4, 24), datetime.date(2023, 4, 25), datetime.date(2023, 4, 26), datetime.date(2023, 4, 27), datetime.date(2023, 4, 28), datetime.date(2023, 4, 29), datetime.date(2023, 4, 30), datetime.date(2023, 5, 1), datetime.date(2023, 5, 2), datetime.date(2023, 5, 3), datetime.date(2023, 5, 4), datetime.date(2023, 5, 5), datetime.date(2023, 5, 6), datetime.date(2023, 5, 7), datetime.date(2023, 5, 8), datetime.date(2023, 5, 15), datetime.date(2023, 5, 16), datetime.date(2023, 5, 17), datetime.date(2023, 5, 18), datetime.date(2023, 5, 19), datetime.date(2023, 5, 20), datetime.date(2023, 5, 21), datetime.date(2023, 5, 22), datetime.date(2023, 5, 23), datetime.date(2023, 5, 24), datetime.date(2023, 5, 25), datetime.date(2023, 5, 26), datetime.date(2023, 5, 27), datetime.date(2023, 5, 28), datetime.date(2023, 5, 29), datetime.date(2023, 5, 30), datetime.date(2023, 5, 31), datetime.date(2023, 6, 1), datetime.date(2023, 6, 2), datetime.date(2023, 6, 3), datetime.date(2023, 6, 4), datetime.date(2023, 6, 5), datetime.date(2023, 6, 6), datetime.date(2023, 6, 16), datetime.date(2023, 6, 17), datetime.date(2023, 6, 18), datetime.date(2023, 6, 19), datetime.date(2023, 6, 20), datetime.date(2023, 6, 21), datetime.date(2023, 6, 22), datetime.date(2023, 6, 23), datetime.date(2023, 6, 24), datetime.date(2023, 6, 25), datetime.date(2023, 6, 26), datetime.date(2023, 6, 27), datetime.date(2023, 6, 28), datetime.date(2023, 6, 29), datetime.date(2023, 6, 30), datetime.date(2023, 7, 1), datetime.date(2023, 7, 2), datetime.date(2023, 7, 3), datetime.date(2023, 7, 4), datetime.date(2023, 7, 5), datetime.date(2023, 7, 6), datetime.date(2023, 7, 7), datetime.date(2023, 7, 8), datetime.date(2023, 7, 9), datetime.date(2023, 7, 10), datetime.date(2023, 7, 11), datetime.date(2023, 7, 12), datetime.date(2023, 7, 13), datetime.date(2023, 7, 14), datetime.date(2023, 7, 15), datetime.date(2023, 7, 16), datetime.date(2023, 7, 17), datetime.date(2023, 7, 18), datetime.date(2023, 7, 19), datetime.date(2023, 7, 20), datetime.date(2023, 7, 21), datetime.date(2023, 7, 22), datetime.date(2023, 7, 23), datetime.date(2023, 7, 24), datetime.date(2023, 7, 25), datetime.date(2023, 7, 26), datetime.date(2023, 7, 27), datetime.date(2023, 7, 28), datetime.date(2023, 7, 29), datetime.date(2023, 7, 30), datetime.date(2023, 7, 31), datetime.date(2023, 8, 1), datetime.date(2023, 8, 2), datetime.date(2023, 8, 3), datetime.date(2023, 8, 4), datetime.date(2023, 8, 5), datetime.date(2023, 8, 6), datetime.date(2023, 8, 7), datetime.date(2023, 8, 8), datetime.date(2023, 8, 9), datetime.date(2023, 8, 10), datetime.date(2023, 8, 11), datetime.date(2023, 8, 12), datetime.date(2023, 8, 13), datetime.date(2023, 8, 14), datetime.date(2023, 8, 15), datetime.date(2023, 8, 16), datetime.date(2023, 8, 17), datetime.date(2023, 8, 18), datetime.date(2023, 8, 19), datetime.date(2023, 8, 20), datetime.date(2023, 8, 21), datetime.date(2023, 8, 22), datetime.date(2023, 8, 23), datetime.date(2023, 8, 24), datetime.date(2023, 8, 25), datetime.date(2023, 8, 26), datetime.date(2023, 8, 27), datetime.date(2023, 8, 28), datetime.date(2023, 8, 29), datetime.date(2023, 8, 30), datetime.date(2023, 8, 31), datetime.date(2023, 9, 1), datetime.date(2023, 9, 2), datetime.date(2023, 9, 3), datetime.date(2023, 9, 4), datetime.date(2023, 9, 5), datetime.date(2023, 9, 6), datetime.date(2023, 9, 7), datetime.date(2023, 9, 8), datetime.date(2023, 9, 9), datetime.date(2023, 9, 10), datetime.date(2023, 9, 11), datetime.date(2023, 9, 12), datetime.date(2023, 9, 13), datetime.date(2023, 9, 14), datetime.date(2023, 9, 15), datetime.date(2023, 9, 16), datetime.date(2023, 9, 17), datetime.date(2023, 9, 18), datetime.date(2023, 9, 19), datetime.date(2023, 9, 20), datetime.date(2023, 9, 21), datetime.date(2023, 9, 22), datetime.date(2023, 9, 23), datetime.date(2023, 9, 24), datetime.date(2023, 9, 25), datetime.date(2023, 9, 26), datetime.date(2023, 9, 27), datetime.date(2023, 9, 28), datetime.date(2023, 9, 29), datetime.date(2023, 9, 30), datetime.date(2023, 10, 1), datetime.date(2023, 10, 2), datetime.date(2023, 10, 3), datetime.date(2023, 10, 4), datetime.date(2023, 10, 5), datetime.date(2023, 10, 6), datetime.date(2023, 10, 7), datetime.date(2023, 10, 8), datetime.date(2023, 10, 9), datetime.date(2023, 10, 10), datetime.date(2023, 10, 11), datetime.date(2023, 10, 12), datetime.date(2023, 10, 13), datetime.date(2023, 10, 14), datetime.date(2023, 10, 15), datetime.date(2023, 10, 16), datetime.date(2023, 10, 17), datetime.date(2023, 10, 18), datetime.date(2023, 10, 19), datetime.date(2023, 10, 20), datetime.date(2023, 10, 21), datetime.date(2023, 10, 25), datetime.date(2023, 10, 26), datetime.date(2023, 10, 27), datetime.date(2023, 10, 28), datetime.date(2023, 10, 29), datetime.date(2023, 10, 30), datetime.date(2023, 10, 31), datetime.date(2023, 11, 1), datetime.date(2023, 11, 2), datetime.date(2023, 11, 3), datetime.date(2023, 11, 4), datetime.date(2023, 11, 5), datetime.date(2023, 11, 6), datetime.date(2023, 11, 7), datetime.date(2023, 11, 8), datetime.date(2023, 11, 9), datetime.date(2023, 11, 10), datetime.date(2023, 11, 11), datetime.date(2023, 11, 12), datetime.date(2023, 11, 13), datetime.date(2023, 11, 14), datetime.date(2023, 11, 15), datetime.date(2023, 11, 16), datetime.date(2023, 11, 17), datetime.date(2023, 11, 18), datetime.date(2023, 11, 19), datetime.date(2023, 11, 20), datetime.date(2023, 11, 21), datetime.date(2023, 11, 22), datetime.date(2023, 11, 23), datetime.date(2023, 11, 24), datetime.date(2023, 11, 25), datetime.date(2023, 11, 26), datetime.date(2023, 11, 27), datetime.date(2023, 11, 28), datetime.date(2023, 11, 29), datetime.date(2023, 11, 30), datetime.date(2023, 12, 1), datetime.date(2023, 12, 2), datetime.date(2023, 12, 6), datetime.date(2023, 12, 7), datetime.date(2023, 12, 8), datetime.date(2023, 12, 9), datetime.date(2023, 12, 10), datetime.date(2023, 12, 11), datetime.date(2023, 12, 12), datetime.date(2023, 12, 13), datetime.date(2023, 12, 14), datetime.date(2023, 12, 15), datetime.date(2023, 12, 16), datetime.date(2023, 12, 17), datetime.date(2023, 12, 18), datetime.date(2023, 12, 19), datetime.date(2023, 12, 20), datetime.date(2023, 12, 21), datetime.date(2023, 12, 22), datetime.date(2023, 12, 23), datetime.date(2023, 12, 24), datetime.date(2023, 12, 25), datetime.date(2023, 12, 26), datetime.date(2023, 12, 27), datetime.date(2023, 12, 28), datetime.date(2023, 12, 29), datetime.date(2023, 12, 30), datetime.date(2023, 12, 31), datetime.date(2024, 1, 1), datetime.date(2024, 1, 2), datetime.date(2024, 1, 3), datetime.date(2024, 1, 4), datetime.date(2024, 1, 5), datetime.date(2024, 1, 6), datetime.date(2024, 1, 7), datetime.date(2024, 1, 8), datetime.date(2024, 1, 9), datetime.date(2024, 1, 10), datetime.date(2024, 1, 11), datetime.date(2024, 1, 12), datetime.date(2024, 1, 13), datetime.date(2024, 1, 14), datetime.date(2024, 1, 15), datetime.date(2024, 1, 16), datetime.date(2024, 1, 17), datetime.date(2024, 1, 18), datetime.date(2024, 1, 19), datetime.date(2024, 1, 20), datetime.date(2024, 1, 21), datetime.date(2024, 1, 22), datetime.date(2024, 1, 23), datetime.date(2024, 1, 24), datetime.date(2024, 1, 25), datetime.date(2024, 1, 26), datetime.date(2024, 1, 27), datetime.date(2024, 1, 28), datetime.date(2024, 1, 29), datetime.date(2024, 1, 30), datetime.date(2024, 1, 31), datetime.date(2024, 2, 1), datetime.date(2024, 2, 2), datetime.date(2024, 2, 3), datetime.date(2024, 2, 4), datetime.date(2024, 2, 5), datetime.date(2024, 2, 6), datetime.date(2024, 2, 7), datetime.date(2024, 2, 8), datetime.date(2024, 2, 9), datetime.date(2024, 2, 10), datetime.date(2024, 2, 11), datetime.date(2024, 2, 12), datetime.date(2024, 2, 13), datetime.date(2024, 2, 14), datetime.date(2024, 2, 15), datetime.date(2024, 2, 16), datetime.date(2024, 2, 17), datetime.date(2024, 2, 18), datetime.date(2024, 2, 19), datetime.date(2024, 2, 20), datetime.date(2024, 2, 21), datetime.date(2024, 2, 22), datetime.date(2024, 2, 23), datetime.date(2024, 2, 24), datetime.date(2024, 2, 25), datetime.date(2024, 2, 26), datetime.date(2024, 2, 27), datetime.date(2024, 2, 28), datetime.date(2024, 2, 29), datetime.date(2024, 3, 1), datetime.date(2024, 3, 2), datetime.date(2024, 3, 3), datetime.date(2024, 3, 4), datetime.date(2024, 3, 5), datetime.date(2024, 3, 6), datetime.date(2024, 3, 7), datetime.date(2024, 3, 8), datetime.date(2024, 3, 9), datetime.date(2024, 3, 10), datetime.date(2024, 3, 11), datetime.date(2024, 3, 12), datetime.date(2024, 3, 13), datetime.date(2024, 3, 14), datetime.date(2024, 3, 15), datetime.date(2024, 3, 16), datetime.date(2024, 3, 17), datetime.date(2024, 3, 18), datetime.date(2024, 3, 19), datetime.date(2024, 3, 20), datetime.date(2024, 3, 21), datetime.date(2024, 3, 22), datetime.date(2024, 3, 23), datetime.date(2024, 3, 24), datetime.date(2024, 3, 25), datetime.date(2024, 3, 26), datetime.date(2024, 3, 27), datetime.date(2024, 3, 28), datetime.date(2024, 3, 29), datetime.date(2024, 3, 30), datetime.date(2024, 3, 31), datetime.date(2024, 4, 1), datetime.date(2024, 4, 2), datetime.date(2024, 4, 3), datetime.date(2024, 4, 4), datetime.date(2024, 4, 5), datetime.date(2024, 4, 6), datetime.date(2024, 4, 7), datetime.date(2024, 4, 8), datetime.date(2024, 4, 9), datetime.date(2024, 4, 10), datetime.date(2024, 4, 11), datetime.date(2024, 4, 12), datetime.date(2024, 4, 13), datetime.date(2024, 4, 14), datetime.date(2024, 4, 15), datetime.date(2024, 4, 16), datetime.date(2024, 4, 17), datetime.date(2024, 4, 18), datetime.date(2024, 4, 19), datetime.date(2024, 4, 20), datetime.date(2024, 4, 21), datetime.date(2024, 4, 22), datetime.date(2024, 4, 23), datetime.date(2024, 4, 24), datetime.date(2024, 4, 25), datetime.date(2024, 4, 26), datetime.date(2024, 4, 27), datetime.date(2024, 4, 28), datetime.date(2024, 4, 29), datetime.date(2024, 4, 30), datetime.date(2024, 5, 1), datetime.date(2024, 5, 2), datetime.date(2024, 5, 3), datetime.date(2024, 5, 4), datetime.date(2024, 5, 5), datetime.date(2024, 5, 6), datetime.date(2024, 5, 7), datetime.date(2024, 5, 8), datetime.date(2024, 5, 9), datetime.date(2024, 5, 10), datetime.date(2024, 5, 11), datetime.date(2024, 5, 12), datetime.date(2024, 5, 13), datetime.date(2024, 5, 14), datetime.date(2024, 5, 15), datetime.date(2024, 5, 16), datetime.date(2024, 5, 17), datetime.date(2024, 5, 18), datetime.date(2024, 5, 19), datetime.date(2024, 5, 20), datetime.date(2024, 5, 21), datetime.date(2024, 5, 22), datetime.date(2024, 5, 23), datetime.date(2024, 5, 24), datetime.date(2024, 5, 25), datetime.date(2024, 5, 28), datetime.date(2024, 5, 29), datetime.date(2024, 5, 30), datetime.date(2024, 5, 31), datetime.date(2024, 6, 1), datetime.date(2024, 6, 2), datetime.date(2024, 6, 3), datetime.date(2024, 6, 4), datetime.date(2024, 6, 5), datetime.date(2024, 6, 6), datetime.date(2024, 6, 7), datetime.date(2024, 6, 8), datetime.date(2024, 6, 9), datetime.date(2024, 6, 10), datetime.date(2024, 6, 12), datetime.date(2024, 6, 13), datetime.date(2024, 6, 14), datetime.date(2024, 6, 15), datetime.date(2024, 6, 16), datetime.date(2024, 6, 17), datetime.date(2024, 6, 18), datetime.date(2024, 6, 19), datetime.date(2024, 6, 20), datetime.date(2024, 6, 21), datetime.date(2024, 6, 22), datetime.date(2024, 6, 23), datetime.date(2024, 6, 24), datetime.date(2024, 6, 25), datetime.date(2024, 6, 26), datetime.date(2024, 6, 27), datetime.date(2024, 6, 28), datetime.date(2024, 6, 29), datetime.date(2024, 6, 30), datetime.date(2024, 7, 1), datetime.date(2024, 7, 2), datetime.date(2024, 7, 3), datetime.date(2024, 7, 4), datetime.date(2024, 7, 5), datetime.date(2024, 7, 6), datetime.date(2024, 7, 7), datetime.date(2024, 7, 8), datetime.date(2024, 7, 9), datetime.date(2024, 7, 10), datetime.date(2024, 7, 11), datetime.date(2024, 7, 12), datetime.date(2024, 7, 13), datetime.date(2024, 7, 14), datetime.date(2024, 7, 15), datetime.date(2024, 7, 16), datetime.date(2024, 7, 17), datetime.date(2024, 7, 18), datetime.date(2024, 7, 19), datetime.date(2024, 7, 20), datetime.date(2024, 7, 21), datetime.date(2024, 7, 22), datetime.date(2024, 7, 23), datetime.date(2024, 7, 24), datetime.date(2024, 7, 25), datetime.date(2024, 7, 26), datetime.date(2024, 7, 27), datetime.date(2024, 7, 28), datetime.date(2024, 7, 29), datetime.date(2024, 7, 30), datetime.date(2024, 7, 31), datetime.date(2024, 8, 1), datetime.date(2024, 8, 2), datetime.date(2024, 8, 3), datetime.date(2024, 8, 4), datetime.date(2024, 8, 5), datetime.date(2024, 8, 6), datetime.date(2024, 8, 7), datetime.date(2024, 8, 8), datetime.date(2024, 8, 9), datetime.date(2024, 8, 10), datetime.date(2024, 8, 11), datetime.date(2024, 8, 12), datetime.date(2024, 8, 13), datetime.date(2024, 8, 14), datetime.date(2024, 8, 15), datetime.date(2024, 8, 16), datetime.date(2024, 8, 17), datetime.date(2024, 8, 18), datetime.date(2024, 8, 19), datetime.date(2024, 8, 20), datetime.date(2024, 8, 21), datetime.date(2024, 8, 22), datetime.date(2024, 8, 23), datetime.date(2024, 8, 24), datetime.date(2024, 8, 25), datetime.date(2024, 8, 26), datetime.date(2024, 8, 27), datetime.date(2024, 8, 28), datetime.date(2024, 8, 29), datetime.date(2024, 8, 30), datetime.date(2024, 8, 31), datetime.date(2024, 9, 1), datetime.date(2024, 9, 2), datetime.date(2024, 9, 3), datetime.date(2024, 9, 4), datetime.date(2024, 9, 5), datetime.date(2024, 9, 6), datetime.date(2024, 9, 7), datetime.date(2024, 9, 8), datetime.date(2024, 9, 9), datetime.date(2024, 9, 10), datetime.date(2024, 9, 11), datetime.date(2024, 9, 12), datetime.date(2024, 9, 13), datetime.date(2024, 9, 14), datetime.date(2024, 9, 15), datetime.date(2024, 9, 16), datetime.date(2024, 9, 17), datetime.date(2024, 9, 18), datetime.date(2024, 9, 19), datetime.date(2024, 9, 20), datetime.date(2024, 9, 21), datetime.date(2024, 9, 22), datetime.date(2024, 9, 23), datetime.date(2024, 9, 24), datetime.date(2024, 9, 25), datetime.date(2024, 9, 26), datetime.date(2024, 9, 27), datetime.date(2024, 9, 28), datetime.date(2024, 9, 29), datetime.date(2024, 9, 30), datetime.date(2024, 10, 1), datetime.date(2024, 10, 2), datetime.date(2024, 10, 3), datetime.date(2024, 10, 4), datetime.date(2024, 10, 5), datetime.date(2024, 10, 6), datetime.date(2024, 10, 7), datetime.date(2024, 10, 8), datetime.date(2024, 10, 9), datetime.date(2024, 10, 10), datetime.date(2024, 10, 11), datetime.date(2024, 10, 12), datetime.date(2024, 10, 13), datetime.date(2024, 10, 14), datetime.date(2024, 10, 15), datetime.date(2024, 10, 16), datetime.date(2024, 10, 17), datetime.date(2024, 10, 18), datetime.date(2024, 10, 19), datetime.date(2024, 10, 20), datetime.date(2024, 10, 21), datetime.date(2024, 10, 22), datetime.date(2024, 10, 23), datetime.date(2024, 10, 24), datetime.date(2024, 10, 25), datetime.date(2024, 10, 26), datetime.date(2024, 10, 27), datetime.date(2024, 10, 28), datetime.date(2024, 10, 29), datetime.date(2024, 10, 30), datetime.date(2024, 10, 31), datetime.date(2024, 11, 1), datetime.date(2024, 11, 2), datetime.date(2024, 11, 3), datetime.date(2024, 11, 4), datetime.date(2024, 11, 5), datetime.date(2024, 11, 6), datetime.date(2024, 11, 7), datetime.date(2024, 11, 8), datetime.date(2024, 11, 9), datetime.date(2024, 11, 10), datetime.date(2024, 11, 11), datetime.date(2024, 11, 12), datetime.date(2024, 11, 13), datetime.date(2024, 11, 14), datetime.date(2024, 11, 15), datetime.date(2024, 11, 16), datetime.date(2024, 11, 17), datetime.date(2024, 11, 18), datetime.date(2024, 11, 19), datetime.date(2024, 11, 20), datetime.date(2024, 11, 21), datetime.date(2024, 11, 22), datetime.date(2024, 11, 23), datetime.date(2024, 11, 24), datetime.date(2024, 11, 25), datetime.date(2024, 11, 26), datetime.date(2024, 11, 27), datetime.date(2024, 11, 28), datetime.date(2024, 11, 29), datetime.date(2024, 11, 30), datetime.date(2024, 12, 1), datetime.date(2024, 12, 2), datetime.date(2024, 12, 3), datetime.date(2024, 12, 4), datetime.date(2024, 12, 5), datetime.date(2024, 12, 6), datetime.date(2024, 12, 7), datetime.date(2024, 12, 8), datetime.date(2024, 12, 9), datetime.date(2024, 12, 10), datetime.date(2024, 12, 11), datetime.date(2024, 12, 12), datetime.date(2024, 12, 13), datetime.date(2024, 12, 14), datetime.date(2024, 12, 15), datetime.date(2024, 12, 16), datetime.date(2024, 12, 17), datetime.date(2024, 12, 18), datetime.date(2024, 12, 19), datetime.date(2024, 12, 20), datetime.date(2024, 12, 21), datetime.date(2024, 12, 22), datetime.date(2024, 12, 23), datetime.date(2024, 12, 24), datetime.date(2024, 12, 25), datetime.date(2024, 12, 26), datetime.date(2024, 12, 27), datetime.date(2024, 12, 28), datetime.date(2024, 12, 29), datetime.date(2024, 12, 30), datetime.date(2024, 12, 31)]
Total Unique Dates: 707

In [17]:
min_lat, max_lat = 999, -999
min_lon, max_lon = 999, -999

for i in range(parquet_file.num_row_groups):
    df = parquet_file.read_row_group(i, columns=["latitude", "longitude"]).to_pandas()
    
    min_lat = min(min_lat, df["latitude"].min())
    max_lat = max(max_lat, df["latitude"].max())
    min_lon = min(min_lon, df["longitude"].min())
    max_lon = max(max_lon, df["longitude"].max())

print("Latitude Min:", min_lat)
print("Latitude Max:", max_lat)
print("Longitude Min:", min_lon)
print("Longitude Max:", max_lon)

Latitude Min: 7.549999999999997
Latitude Max: 35.949999999999996
Longitude Min: 68.05
Longitude Max: 97.85

In [18]:
null_count = 0
total_count = 0

for i in range(parquet_file.num_row_groups):
    df = parquet_file.read_row_group(i, columns=["AOD"]).to_pandas()
    
    null_count += df["AOD"].isna().sum()
    total_count += len(df)

print("Total rows:", total_count)
print("Null AOD rows:", null_count)
print("Null %:", (null_count / total_count) * 100)

Total rows: 51360120
Null AOD rows: 0
Null %: 0.0

In [5]:
import dask.dataframe as dd
df = dd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\insat_daily\insatdaily_grid.parquet")

In [6]:
rows = df.shape[0].compute()

# Columns
cols = df.shape[1]

print("Shape:", (rows, cols))

Shape: (9928398, 8)

In [7]:
df.isnull().sum().compute()

lat_round       0
lon_round       0
date            0
AOD_mean        0
AOD_max         0
AOD_p75         0
AOD_count       0
AOD_coverage    0
dtype: int64

In [1]:
import dask.dataframe as dd
import os
import shutil

original_file = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\insat_daily\insat_daily_grid.parquet"
temp_file = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\insat_daily\insat_indiadaily.parquet"

# Load parquet
df = dd.read_parquet(original_file)

# Drop AOD_std if exists
if 'AOD_std' in df.columns:
    df = df.drop(columns=['AOD_std'])

print("Updated columns:", df.columns)

# Save to temporary parquet
df.to_parquet(temp_file, write_index=False)

# Delete original file
if os.path.exists(original_file):
    os.remove(original_file)

# Rename temp file to original file name
os.rename(temp_file, original_file)

print("Original file updated (AOD_std removed).")

Updated columns: Index(['lat_round', 'lon_round', 'date', 'AOD_mean', 'AOD_max', 'AOD_p75',
       'AOD_count', 'AOD_coverage'],
      dtype='object')
Original file updated (AOD_std removed).

In [8]:
df.head()

,lat_round,lon_round,date,AOD_mean,AOD_max,AOD_p75,AOD_count,AOD_coverage
0,7.55,77.35,2023-01-02,0.171448,0.208544,0.171448,2,0.285714
1,7.55,77.35,2023-01-03,0.191858,0.263068,0.191858,6,0.857143
2,7.55,77.35,2023-01-04,0.294082,0.314460,0.294082,4,0.571429
3,7.55,77.35,2023-01-05,0.233201,0.268513,0.233201,7,1.000000
4,7.55,77.35,2023-01-07,0.305637,0.387881,0.305637,7,1.000000

In [9]:
import dask.dataframe as dd

file = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\insat_daily\insatdaily_grid.parquet"

df = dd.read_parquet(file, columns=['lat_round', 'lon_round'])

# Drop duplicates
unique_grids = df.drop_duplicates()

# Count unique pairs
count = unique_grids.shape[0].compute()

print("Unique lat-lon grid points:", count)

Unique lat-lon grid points: 31033

In [23]:
import pyarrow.parquet as pq

file_path = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\insat_daily\insat_daily_grid.parquet"
parquet_file = pq.ParquetFile(file_path)


print("Number of row groups:", parquet_file.num_row_groups)
print("Schema:")
print(parquet_file.schema)

Number of row groups: 10
Schema:
<pyarrow._parquet.ParquetSchema object at 0x000002B855F05A00>
required group field_id=-1 schema {
  optional double field_id=-1 lat_round;
  optional double field_id=-1 lon_round;
  optional int32 field_id=-1 date (Date);
  optional float field_id=-1 AOD_mean;
  optional float field_id=-1 AOD_max;
  optional float field_id=-1 AOD_std;
  optional float field_id=-1 AOD_p75;
  optional int64 field_id=-1 AOD_count;
  optional double field_id=-1 AOD_coverage;
}

In [29]:
import pandas as pd

df = pd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\insat_daily\insat_daily_grid.parquet", columns=["date"])

unique_dates = df["date"].drop_duplicates().sort_values()

print(unique_dates)
print("Total unique dates:", len(unique_dates))

279      2023-01-01
0        2023-01-02
1        2023-01-03
2        2023-01-04
3        2023-01-05
            ...
277      2024-12-27
5277     2024-12-28
278      2024-12-29
11825    2024-12-30
68782    2024-12-31
Name: date, Length: 706, dtype: object
Total unique dates: 706

In [28]:
min_lat, max_lat = 999, -999
min_lon, max_lon = 999, -999

for i in range(parquet_file.num_row_groups):
    df = parquet_file.read_row_group(i, columns=["lat_round", "lon_round"]).to_pandas()
    
    min_lat = min(min_lat, df["lat_round"].min())
    max_lat = max(max_lat, df["lat_round"].max())
    min_lon = min(min_lon, df["lon_round"].min())
    max_lon = max(max_lon, df["lon_round"].max())

print("Latitude Min:", min_lat)
print("Latitude Max:", max_lat)
print("Longitude Min:", min_lon)
print("Longitude Max:", max_lon)

Latitude Min: 7.55
Latitude Max: 35.15
Longitude Min: 68.05
Longitude Max: 97.85

In [22]:
import pandas as pd

FILE = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\spatial_join\insat_station_daily.parquet"

df = pd.read_parquet(FILE)

# =========================
# BASIC INFO
# =========================
print("Total rows:", len(df))
print("Columns:", df.columns.tolist())

# =========================
# UNIQUE DATES
# =========================
unique_dates = df['date'].nunique()
print("\nUnique dates:", unique_dates)

print("Date range:", df['date'].min(), "to", df['date'].max())

# =========================
# UNIQUE STATIONS (proxy for lat-lon)
# =========================
unique_stations = df['station_name'].nunique()
print("\nUnique stations:", unique_stations)

# =========================
# CHECK DUPLICATES (important)
# =========================
dup = df.duplicated(subset=['station_name', 'date']).sum()
print("\nDuplicate (station_name, date) rows:", dup)

# =========================
# MISSING VALUES
# =========================
print("\nMissing values (%):")
missing = df.isna().mean() * 100
print(missing.sort_values(ascending=False))

# =========================
# FULLY MISSING ROWS (AOD missing case)
# =========================
missing_rows = df[
    df[['AOD_mean', 'AOD_max', 'AOD_p75']].isna().all(axis=1)
]

print("\nRows with NO AOD data:", len(missing_rows))
print("Percentage:", (len(missing_rows)/len(df))*100)

# =========================
# EXPECTED VS ACTUAL
# =========================
expected = unique_stations * unique_dates
print("\nExpected rows:", expected)
print("Actual rows  :", len(df))

if expected == len(df):
    print("✅ Perfect grid (no missing station-date pairs)")
else:
    print("⚠️ Missing station-date combinations detected")

Total rows: 68482
Columns: ['station_name', 'date', 'n_pixels', 'AOD_mean', 'AOD_max', 'AOD_p75', 'AOD_count', 'AOD_coverage']

Unique dates: 706
Date range: 2023-01-01 to 2024-12-31

Unique stations: 97

Duplicate (station_name, date) rows: 0

Missing values (%):
AOD_mean        41.761339
AOD_max         41.761339
AOD_p75         41.761339
station_name     0.000000
n_pixels         0.000000
date             0.000000
AOD_count        0.000000
AOD_coverage     0.000000
dtype: float64

Rows with NO AOD data: 28599
Percentage: 41.76133874594784

Expected rows: 68482
Actual rows  : 68482
✅ Perfect grid (no missing station-date pairs)

In [23]:
df.head()

,station_name,date,n_pixels,AOD_mean,AOD_max,AOD_p75,AOD_count,AOD_coverage
0,Sector 62 Noida,2023-01-01,5,0.978464,1.244282,0.978464,7,1.000000
1,ITO Delhi,2023-01-01,6,0.918637,1.056489,0.918637,7,1.000000
2,DTU Delhi,2023-01-01,7,0.835057,0.910091,0.835057,4,0.571429
3,R K Puram Delhi,2023-01-01,5,0.813867,0.877527,0.813867,4,0.571429
4,Punjabi Bagh Delhi,2023-01-01,6,0.794897,0.870788,0.794897,4,0.571429

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Is missingness seasonal? (it should be — monsoon will show ~80-90% missing)
df['month'] = pd.to_datetime(df['date']).dt.month
monthly_missing = df.groupby('month')['AOD_mean'].apply(
    lambda x: x.isna().mean() * 100
)
print(monthly_missing)
# Expected pattern:
# Jan-Mar (Winter)     : 20-30% missing
# Jun-Sep (Monsoon)    : 70-90% missing  ← clouds dominate
# Oct-Dec (Post-monsoon): 30-40% missing

# 2. Is missingness station-specific?
station_missing = df.groupby('station_name')['AOD_mean'].apply(
    lambda x: x.isna().mean() * 100
).sort_values(ascending=False)
print(station_missing.head(10))
# If some stations show 80%+ missing — they may be in chronically cloudy regions
# Flag these stations — their AOD signal will be weak regardless

# 3. Does PM25 differ on missing vs present AOD days?
# pm_with_aod    = df[df['AOD_mean'].notna()]['pm25'].mean()
# pm_without_aod = df[df['AOD_mean'].isna()]['pm25'].mean()
# print(f"PM25 when AOD present : {pm_with_aod:.1f} µg/m³")
# print(f"PM25 when AOD missing : {pm_without_aod:.1f} µg/m³")
# This tells you how much information you're losing on cloud days

month
1     23.511806
2     11.557244
3     17.326239
4     19.467354
5     31.691485
6     61.422680
7     92.750249
8     89.590954
9     71.907216
10    28.208319
11    26.546392
12    25.318889
Name: AOD_mean, dtype: float64
station_name
Belur Math Howrah                 100.000000
Collectorate Jodhpur               99.716714
Bombay Castel Ooty                 70.113314
Lumpyngngad Shillong Meghalaya     64.589235
Sanjay Palace Agra                 62.464589
BTM Layout Bengaluru               62.039660
Silk Board Bengaluru               60.623229
Jayanagar 5th Block Bengaluru      60.481586
Hebbal Bengaluru                   60.198300
Peenya Bengaluru                   59.065156
Name: AOD_mean, dtype: float64

In [25]:
# Calculate per-station AOD missing rate
station_missing_rate = df.groupby('station_name')['AOD_mean'].apply(
    lambda x: (x == -1).mean()  # after sentinel fill
).reset_index()
station_missing_rate.columns = ['station_name', 'aod_missing_rate']

# Categorize stations by AOD reliability
def station_aod_category(rate):
    if rate >= 0.95:
        return 'dead'          # AOD useless — 95%+ missing
    elif rate >= 0.60:
        return 'poor'          # AOD weak signal
    elif rate >= 0.40:
        return 'moderate'      # monsoon-affected but usable
    else:
        return 'good'          # reliable AOD

station_missing_rate['aod_quality_cat'] = station_missing_rate[
    'aod_missing_rate'
].apply(station_aod_category)

print(station_missing_rate['aod_quality_cat'].value_counts())

# Merge this back into main df as a feature
df = df.merge(station_missing_rate, on='station_name', how='left')

# Encode category
cat_map = {'dead': 0, 'poor': 1, 'moderate': 2, 'good': 3}
df['station_aod_quality'] = df['aod_quality_cat'].map(cat_map)

aod_quality_cat
good    97
Name: count, dtype: int64

In [26]:
dead_stations = station_missing_rate[
    station_missing_rate['aod_quality_cat'] == 'dead'
]['station_name'].tolist()

poor_stations = station_missing_rate[
    station_missing_rate['aod_quality_cat'] == 'poor'
]['station_name'].tolist()

print(f"Dead stations ({len(dead_stations)}):", dead_stations)
print(f"Poor stations ({len(poor_stations)}):", poor_stations)

Dead stations (0): []
Poor stations (0): []

In [27]:
# Compute mean AOD per station per month — only from valid (non -1) days
valid_aod = df[df['AOD_mean'] != -1].copy()

station_month_aod = valid_aod.groupby(
    ['station_name', 'month']
)['AOD_mean'].agg(['mean', 'count']).reset_index()

station_month_aod.columns = [
    'station_name', 'month', 
    'station_month_aod_clim',   # climatological AOD for this station-month
    'station_month_aod_n'       # how many days this is based on
]

df = df.merge(station_month_aod, on=['station_name', 'month'], how='left')

# If station-month climatology itself is missing (dead station + month)
# fill with overall India monthly mean
india_month_aod = valid_aod.groupby('month')['AOD_mean'].mean()
df['station_month_aod_clim'] = df.apply(
    lambda row: india_month_aod.get(row['month'], 0.3)
    if pd.isna(row['station_month_aod_clim'])
    else row['station_month_aod_clim'],
    axis=1
)

# Reliability weight — how trustworthy is that climatology?
# Low n = unreliable climatology
df['aod_clim_reliability'] = np.minimum(
    df['station_month_aod_n'].fillna(0) / 30, 1.0
)  # caps at 1.0 after 30 observations

In [28]:
blr_stations = [s for s in df['station_name'].unique() if 'Bengaluru' in s]

blr_missing = df[df['station_name'].isin(blr_stations)].groupby(
    'month'
)['AOD_mean'].apply(lambda x: (x == -1).mean() * 100)

print("Bengaluru AOD missing by month:")
print(blr_missing.round(1))

# If non-monsoon months (Jan-May, Oct-Dec) still show >40% missing
# it may be a retrieval geometry issue — flag these stations differently
blr_nonmonsoon_missing = blr_missing[[1,2,3,4,5,10,11,12]].mean()
print(f"\nBengaluru non-monsoon missing: {blr_nonmonsoon_missing:.1f}%")

if blr_nonmonsoon_missing > 40:
    print("⚠ Geometric/systematic retrieval issue — treat like poor stations")
    df.loc[df['station_name'].isin(blr_stations), 'station_aod_quality'] = 1

Bengaluru AOD missing by month:
month
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
Name: AOD_mean, dtype: float64

Bengaluru non-monsoon missing: 0.0%

In [29]:
# More nuanced than a single AOD_missing flag
# Model needs to know: "missing in July" is very different from "missing in January"

df['aod_missing_winter']   = ((df['AOD_mean'] == -1) & 
                               df['month'].isin([12,1,2])).astype(int)
df['aod_missing_premonsoon']= ((df['AOD_mean'] == -1) & 
                                df['month'].isin([3,4,5])).astype(int)
df['aod_missing_monsoon']   = ((df['AOD_mean'] == -1) & 
                                df['month'].isin([6,7,8,9])).astype(int)
df['aod_missing_postmonsoon']= ((df['AOD_mean'] == -1) & 
                                 df['month'].isin([10,11])).astype(int)

In [31]:
df.head()

,station_name,date,n_pixels,AOD_mean,AOD_max,AOD_p75,AOD_count,AOD_coverage,month,aod_missing_rate,aod_quality_cat,station_aod_quality,station_month_aod_clim,station_month_aod_n,aod_clim_reliability,aod_missing_winter,aod_missing_premonsoon,aod_missing_monsoon,aod_missing_postmonsoon
0,Sector 62 Noida,2023-01-01,5,0.978464,1.244282,0.978464,7,1.000000,1,0.0,good,3,1.151048,47,1.0,0,0,0,0
1,ITO Delhi,2023-01-01,6,0.918637,1.056489,0.918637,7,1.000000,1,0.0,good,3,1.096681,48,1.0,0,0,0,0
2,DTU Delhi,2023-01-01,7,0.835057,0.910091,0.835057,4,0.571429,1,0.0,good,3,0.938084,43,1.0,0,0,0,0
3,R K Puram Delhi,2023-01-01,5,0.813867,0.877527,0.813867,4,0.571429,1,0.0,good,3,0.994317,42,1.0,0,0,0,0
4,Punjabi Bagh Delhi,2023-01-01,6,0.794897,0.870788,0.794897,4,0.571429,1,0.0,good,3,0.933955,41,1.0,0,0,0,0

In [21]:
df.isnull().sum()

station_name                   0
date                           0
n_pixels                       0
AOD_mean                   28599
AOD_max                    28599
AOD_p75                    28599
AOD_count                      0
AOD_coverage                   0
month                          0
aod_missing_rate               0
aod_quality_cat                0
station_aod_quality            0
station_month_aod_clim         0
station_month_aod_n            0
aod_clim_reliability           0
aod_missing_winter             0
aod_missing_premonsoon         0
aod_missing_monsoon            0
aod_missing_postmonsoon        0
dtype: int64

In [32]:
df.shape

(68482, 19)

In [2]:
import dask.dataframe as dd
df = dd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\spatial_join\insat_station_daily.parquet")
df1 = dd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\spatial_join\merra_station_daily.parquet")

In [4]:
df.head()

,station_name,date,n_pixels,AOD_mean,AOD_max,AOD_p75,AOD_count,AOD_coverage
0,Sector 62 Noida,2023-01-01,5,0.978464,1.244282,0.978464,7,1.000000
1,ITO Delhi,2023-01-01,6,0.918637,1.056489,0.918637,7,1.000000
2,DTU Delhi,2023-01-01,7,0.835057,0.910091,0.835057,4,0.571429
3,R K Puram Delhi,2023-01-01,5,0.813867,0.877527,0.813867,4,0.571429
4,Punjabi Bagh Delhi,2023-01-01,6,0.794897,0.870788,0.794897,4,0.571429

In [27]:
print(df.columns)
print(df.shape[0].compute())

Index(['station_name', 'date', 'n_pixels', 'AOD_mean', 'AOD_max', 'AOD_p75',
       'AOD_count', 'AOD_coverage'],
      dtype='object')
68482

In [25]:
df.isnull().sum().compute()

station_name        0
date                0
n_pixels            0
AOD_mean        28599
AOD_max         28599
AOD_p75         28599
AOD_count           0
AOD_coverage        0
dtype: int64

In [10]:
df1.head()

,station_name,date,PBLH_mean,PBLH_min,PBLH_max,TLML_mean,TLML_max,moisture_mean,moisture_max,SPEED_mean,SPEED_min,PRECTOT_sum,vent_coeff_mean,vent_coeff_min,inversion_proxy_mean,inversion_proxy_max,wind_dir_mean,PBLH_morning_mean,PBLH_morning_min
0,Sector 62 Noida,2023-01-01,397.121272,62.501790,1606.181754,287.391716,291.834930,4.210141,4.596994,1.996576,1.197900,1.446804e-17,747.056773,82.599158,3.282667,4.451987,285.534906,88.720278,62.501790
1,ITO Delhi,2023-01-01,399.623870,62.501815,1604.174628,287.399849,291.881780,4.193925,4.540281,1.971040,1.136127,1.328727e-17,762.165183,78.415429,3.267063,4.451969,278.414925,93.832402,62.501815
2,DTU Delhi,2023-01-01,402.661050,62.507588,1607.252416,287.387549,291.905809,4.274304,4.584352,2.060942,1.172816,1.679799e-17,803.143300,83.388538,3.244245,4.452061,279.795762,104.479195,62.507588
3,R K Puram Delhi,2023-01-01,398.314549,62.497915,1594.300259,287.406192,291.892512,4.132524,4.452865,1.874832,1.042732,9.165288e-18,747.714637,69.515044,3.268817,4.451898,270.369435,90.521994,62.497915
4,Punjabi Bagh Delhi,2023-01-01,403.378096,62.503915,1606.960470,287.406427,291.933358,4.206682,4.517335,1.990871,1.110166,1.403098e-17,788.303284,78.023516,3.247057,4.451984,273.979765,101.838645,62.503915

In [26]:
df1.isnull().sum().compute()

station_name            0
date                    0
PBLH_mean               0
PBLH_min                0
PBLH_max                0
TLML_mean               0
TLML_max                0
moisture_mean           0
moisture_max            0
SPEED_mean              0
SPEED_min               0
PRECTOT_sum             0
vent_coeff_mean         0
vent_coeff_min          0
inversion_proxy_mean    0
inversion_proxy_max     0
wind_dir_mean           0
PBLH_morning_mean       0
PBLH_morning_min        0
dtype: int64

In [28]:
print(df1.columns)
print(df1.shape[0].compute())

Index(['station_name', 'date', 'PBLH_mean', 'PBLH_min', 'PBLH_max',
       'TLML_mean', 'TLML_max', 'moisture_mean', 'moisture_max', 'SPEED_mean',
       'SPEED_min', 'PRECTOT_sum', 'vent_coeff_mean', 'vent_coeff_min',
       'inversion_proxy_mean', 'inversion_proxy_max', 'wind_dir_mean',
       'PBLH_morning_mean', 'PBLH_morning_min'],
      dtype='object')
71540

In [3]:
df_prefinal = dd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\processed\final_ml_dataset.parquet")

In [7]:
df_final = dd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\processed\final_ml_featured.parquet")

In [8]:
df_prefinal.head()

,date,station_name,pm25,latitude,longitude,n_pixels,AOD_mean,AOD_max,AOD_p75,AOD_count,...,SPEED_mean,SPEED_min,PRECTOT_sum,vent_coeff_mean,vent_coeff_min,inversion_proxy_mean,inversion_proxy_max,wind_dir_mean,PBLH_morning_mean,PBLH_morning_min
0,2023-01-01,Sector 62 Noida,131.027604,28.628,77.3649,5.0,0.978464,1.244282,0.978464,7.0,...,1.996576,1.197900,1.446804e-17,747.056773,82.599158,3.282667,4.451987,285.534906,88.720278,62.501790
1,2023-01-02,Sector 62 Noida,204.667292,28.628,77.3649,0.0,NaN,NaN,NaN,0.0,...,2.732568,1.221766,4.023247e-27,813.739627,133.028073,3.078406,4.451457,299.717118,102.379866,62.316191
2,2023-01-03,Sector 62 Noida,232.663958,28.628,77.3649,5.0,2.416098,2.570632,2.416098,3.0,...,5.108914,2.726804,0.000000e+00,3323.964466,219.997778,2.207823,4.450128,317.792988,90.863709,62.080795
3,2023-01-04,Sector 62 Noida,182.754687,28.628,77.3649,6.0,1.111868,1.203726,1.111868,4.0,...,4.043421,2.261521,0.000000e+00,1015.261216,216.160108,2.966831,4.451210,310.775510,404.106163,166.872214
4,2023-01-05,Sector 62 Noida,259.587500,28.628,77.3649,5.0,1.452860,1.886003,1.452860,4.0,...,3.574554,2.451186,0.000000e+00,589.089737,176.133804,3.404987,4.451395,323.640444,72.879655,61.412179

In [29]:
print(df_prefinal.columns)
print(df_prefinal.shape[0].compute())

Index(['date', 'station_name', 'pm25', 'latitude', 'longitude', 'n_pixels',
       'AOD_mean', 'AOD_max', 'AOD_p75', 'AOD_count', 'AOD_coverage',
       'PBLH_mean', 'PBLH_min', 'PBLH_max', 'TLML_mean', 'TLML_max',
       'moisture_mean', 'moisture_max', 'SPEED_mean', 'SPEED_min',
       'PRECTOT_sum', 'vent_coeff_mean', 'vent_coeff_min',
       'inversion_proxy_mean', 'inversion_proxy_max', 'wind_dir_mean',
       'PBLH_morning_mean', 'PBLH_morning_min'],
      dtype='object')
67970

In [30]:
# 1) Null values in each column
null_counts = df_prefinal.isnull().sum().compute().sort_values(ascending=False)
print("Null values per column:")
print(null_counts)

# Helper to find a column by common naming variants
def pick_col(columns, candidates):
    cols_lower = {c.lower(): c for c in columns}
    for c in candidates:
        if c.lower() in cols_lower:
            return cols_lower[c.lower()]
    return None

cols = list(df_prefinal.columns)

date_col = pick_col(cols, ["date", "datetime", "timestamp", "time", "day"])
lat_col = pick_col(cols, ["latitude", "lat"])
lon_col = pick_col(cols, ["longitude", "lon", "lng"])
station_col = pick_col(cols, ["station_name", "station", "stationid", "station_id", "site"])

# 2) Unique dates
if date_col is not None:
    unique_dates = (
        dd.to_datetime(df_prefinal[date_col], errors="coerce")
        .dropna()
        .dt.normalize()
        .drop_duplicates()
        .compute()
        .sort_values()
    )
    print(f"\nUnique dates ({len(unique_dates)}):")
    print(unique_dates)
else:
    print("\nNo date-like column found. Checked: date/datetime/timestamp/time/day")

# 3) Unique latitude-longitude pairs
if lat_col is not None and lon_col is not None:
    unique_lat_lon = (
        df_prefinal[[lat_col, lon_col]]
        .dropna()
        .drop_duplicates()
        .compute()
        .sort_values([lat_col, lon_col])
        .reset_index(drop=True)
    )
    print(f"\nUnique latitude-longitude pairs ({len(unique_lat_lon)}):")
    print(unique_lat_lon)
else:
    print("\nLatitude/Longitude columns not found. Checked: latitude/lat and longitude/lon/lng")

# 4) Unique station names
if station_col is not None:
    unique_stations = (
        df_prefinal[station_col]
        .dropna()
        .drop_duplicates()
        .compute()
        .sort_values()
        .reset_index(drop=True)
    )
    print(f"\nUnique station names ({len(unique_stations)}):")
    print(unique_stations)
else:
    print("\nNo station column found. Checked: station_name/station/stationid/station_id/site")

Null values per column:
AOD_mean                29921
AOD_p75                 29921
AOD_max                 29921
n_pixels                 2993
AOD_coverage             2993
AOD_count                2993
PBLH_mean                  92
moisture_mean              92
TLML_max                   92
TLML_mean                  92
PBLH_max                   92
PBLH_min                   92
PRECTOT_sum                92
vent_coeff_mean            92
vent_coeff_min             92
inversion_proxy_mean       92
inversion_proxy_max        92
moisture_max               92
SPEED_mean                 92
SPEED_min                  92
PBLH_morning_mean          92
wind_dir_mean              92
PBLH_morning_min           92
longitude                   0
date                        0
station_name                0
pm25                        0
latitude                    0
dtype: int64

Unique dates (731):
0       2023-01-01
1       2023-01-02
2       2023-01-03
3       2023-01-04
4       2023-01-05
           ...
34133   2024-12-27
34134   2024-12-28
34135   2024-12-29
34136   2024-12-30
34137   2024-12-31
Length: 731, dtype: datetime64[ns]

Unique latitude-longitude pairs (98):
    latitude longitude
0    8.51410   76.9477
1    9.96830    76.318
2   11.40427  76.70452
3   11.87020   75.3691
4   12.91000     77.61
..       ...       ...
93  30.73200   76.7726
94  30.90200   75.8083
95  31.08200    76.786
96  31.62000   74.8765
97  82.63000     88.36

[98 rows x 2 columns]

Unique station names (98):
0                     AIIMS Raipur
1              Adarsh Nagar Jaipur
2        Alandur Bus Depot Chennai
3                Anand Vihar Delhi
4           Ardhali Bazar Varanasi
                  ...
93    Vijay Nagar Scheme-78 Indore
94            Vikas Sadan Gurugram
95            Vyttila Kochi Kerala
96       Ward-32 Bapupara Siliguri
97              Zoo Park Hyderabad
Name: station_name, Length: 98, dtype: string

In [9]:
df_final.head()

,date,station_name,pm25,latitude,longitude,n_pixels,AOD_mean,AOD_max,AOD_p75,AOD_count,...,AOD_lag1,AOD_lag2,AOD_roll3,AOD_roll7,station_pm_mean,station_pm_std,station_month_pm,proxy_anomaly,lat,lon
0,2023-01-03,AIIMS Raipur,54.811250,21.2575,81.5775,7,2.062045,2.549567,2.062045,7,...,-1.000000,-1.000000,2.062045,-1.000000,28.675352,18.036318,47.799848,0.079515,21.2575,81.5775
1,2023-01-04,AIIMS Raipur,65.033958,21.2575,81.5775,0,-1.000000,-1.000000,-1.000000,0,...,2.062045,-1.000000,2.062045,-1.000000,28.675352,18.036318,47.799848,-0.940005,21.2575,81.5775
2,2023-01-05,AIIMS Raipur,63.587917,21.2575,81.5775,7,2.145734,2.696037,2.145734,6,...,-1.000000,2.062045,2.103889,-1.000000,28.675352,18.036318,47.799848,0.071047,21.2575,81.5775
3,2023-01-06,AIIMS Raipur,56.248542,21.2575,81.5775,7,0.639584,0.949890,0.639584,7,...,2.145734,-1.000000,1.392659,1.615788,28.675352,18.036318,47.799848,0.070095,21.2575,81.5775
4,2023-01-07,AIIMS Raipur,51.333542,21.2575,81.5775,7,0.285947,0.349989,0.285947,7,...,0.639584,2.145734,1.023755,1.283327,28.675352,18.036318,47.799848,0.064576,21.2575,81.5775

In [31]:
df_final.isnull().sum().compute()

date                0
station_name        0
pm25                0
latitude            0
longitude           0
                   ..
station_pm_std      0
station_month_pm    0
proxy_anomaly       0
lat                 0
lon                 0
Length: 63, dtype: int64

In [11]:
dfpm25india = dd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\insat_daily\insatdaily_grid.parquet")

In [13]:
dfpm25merra = dd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\merra_daily\merra_daily_grid.parquet")

In [17]:
dfpm25india.head()

,lat_round,lon_round,date,AOD_mean,AOD_max,AOD_p75,AOD_count,AOD_coverage
0,7.55,77.35,2023-01-02,0.171448,0.208544,0.171448,2,0.285714
1,7.55,77.35,2023-01-03,0.191858,0.263068,0.191858,6,0.857143
2,7.55,77.35,2023-01-04,0.294082,0.314460,0.294082,4,0.571429
3,7.55,77.35,2023-01-05,0.233201,0.268513,0.233201,7,1.000000
4,7.55,77.35,2023-01-07,0.305637,0.387881,0.305637,7,1.000000

In [18]:
dfpm25merra.head()

,lat_round,lon_round,date,PBLH_mean,PBLH_min,PBLH_max,TLML_mean,TLML_max,moisture_mean,moisture_max,SPEED_mean,SPEED_min,PRECTOT_sum,vent_coeff_mean,vent_coeff_min,inversion_proxy_mean,inversion_proxy_max,wind_dir_mean,PBLH_morning_mean,PBLH_morning_min
0,7.5,77.5,2023-01-01,902.368225,693.783630,1093.887451,299.587128,300.549896,15.050393,15.502608,7.057846,5.248474,0.000001,6377.281250,4014.480469,0.337838,0.432336,218.531723,881.254883,859.190308
1,7.5,77.5,2023-01-02,1154.879028,1010.899536,1576.539795,299.099701,299.580170,14.156573,15.285531,8.155637,7.351015,0.000010,9462.201172,7581.365234,0.263144,0.295196,217.744308,1023.768738,1010.899536
2,7.5,77.5,2023-01-03,1233.849487,1011.184998,1668.796509,299.592010,299.903992,13.928544,14.930469,8.150998,7.276108,0.000025,9936.528320,8360.588867,0.251734,0.295884,218.241684,1586.278076,1573.884277
3,7.5,77.5,2023-01-04,1270.916626,1011.202942,1459.748169,299.886688,300.721802,13.815117,14.571502,9.271119,7.918664,0.000013,11807.703125,8885.229492,0.238691,0.295565,221.805923,1040.728271,1011.202942
4,7.5,77.5,2023-01-05,968.733337,688.263245,1455.347778,299.621246,300.677338,15.417347,16.923286,8.129073,6.266124,0.000140,7670.103027,5274.466309,0.328177,0.435424,229.257553,1262.005615,1143.311157

In [19]:
d1 = dd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\insat_aod_merged.parquet")

In [20]:
d2 = dd.read_parquet(r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\interim\merra_merged.parquet")

In [21]:
d1.head()

                 datetime  latitude  longitude  AOD
39351 2023-02-01 05:45:00     37.95      68.05  NaN
39352 2023-02-01 05:45:00     37.95      68.15  NaN
39353 2023-02-01 05:45:00     37.95      68.25  NaN
39354 2023-02-01 05:45:00     37.95      68.35  NaN
39355 2023-02-01 05:45:00     37.95      68.45  NaN

In [23]:
d1.isnull().sum().compute()

datetime             0
latitude             0
longitude            0
AOD          335204568
dtype: int64

In [22]:
d2.head()

,datetime,latitude,longitude,PBLH,TLML,QLML,ULML,VLML,SPEED,PRECTOT
0,2023-01-01 00:30:00,6.5,68.125,768.71521,299.251068,0.016384,-3.977004,-3.367228,5.214618,9.699725e-07
1,2023-01-01 00:30:00,6.5,68.750,752.21521,299.204193,0.016086,-3.867629,-3.223185,5.036883,6.440096e-07
2,2023-01-01 00:30:00,6.5,69.375,818.96521,299.297943,0.015598,-3.615676,-3.192423,4.825946,1.596636e-07
3,2023-01-01 00:30:00,6.5,70.000,1035.71521,299.594818,0.014808,-3.277786,-3.235392,4.607196,8.381903e-08
4,2023-01-01 00:30:00,6.5,70.625,1085.71521,299.516693,0.014816,-2.962356,-3.307169,4.443133,8.183997e-08

In [32]:
print(df_prefinal[df_prefinal['latitude'] > 38][['station_name','latitude','longitude']])

Dask DataFrame Structure:
              station_name latitude longitude
npartitions=1
                    string  float64    string
                       ...      ...       ...
Dask Name: getitem, 5 expressions
Expr=(Filter(frame=ReadParquetFSSpec(580f257), predicate=ReadParquetFSSpec(580f257)['latitude'] > 38))[['station_name', 'latitude', 'longitude']]

In [33]:
result = df_prefinal[df_prefinal['latitude'] > 38][
    ['station_name', 'latitude', 'longitude']
].compute()

print(result)

            station_name  latitude longitude
20903  Belur Math Howrah     82.63     88.36
20904  Belur Math Howrah     82.63     88.36
20905  Belur Math Howrah     82.63     88.36
20906  Belur Math Howrah     82.63     88.36
20907  Belur Math Howrah     82.63     88.36
...                  ...       ...       ...
55295  Belur Math Howrah     82.63     88.36
55296  Belur Math Howrah     82.63     88.36
55297  Belur Math Howrah     82.63     88.36
55298  Belur Math Howrah     82.63     88.36
55299  Belur Math Howrah     82.63     88.36

[713 rows x 3 columns]

In [35]:
import os

station_lat_lon = df_prefinal[["station_name", "latitude", "longitude"]].dropna().drop_duplicates().compute()
station_lat_lon = station_lat_lon.sort_values(["station_name", "latitude", "longitude"]).reset_index(drop=True)

output_dir = r"C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\raw\cpcb"
os.makedirs(output_dir, exist_ok=True)
output_file = os.path.join(output_dir, "station.csv")

station_lat_lon.to_csv(output_file, index=False)
print(f"Saved {len(station_lat_lon)} rows to {output_file}")

Saved 98 rows to C:\Users\kesha\OneDrive - dtu.ac.in\Desktop\aodtopm25\data\raw\cpcb\station.csv

In [6]:
df_prefinal.head()

,date,station_name,pm25,latitude,longitude,n_pixels,AOD_mean,AOD_max,AOD_p75,AOD_count,...,SPEED_mean,SPEED_min,PRECTOT_sum,vent_coeff_mean,vent_coeff_min,inversion_proxy_mean,inversion_proxy_max,wind_dir_mean,PBLH_morning_mean,PBLH_morning_min
0,2023-01-01,Sector 62 Noida,131.027604,28.628,77.3649,5.0,0.978464,1.244282,0.978464,7.0,...,1.996576,1.197900,1.446804e-17,747.056773,82.599158,3.282667,4.451987,285.534906,88.720278,62.501790
1,2023-01-02,Sector 62 Noida,204.667292,28.628,77.3649,0.0,NaN,NaN,NaN,0.0,...,2.732568,1.221766,4.023247e-27,813.739627,133.028073,3.078406,4.451457,299.717118,102.379866,62.316191
2,2023-01-03,Sector 62 Noida,232.663958,28.628,77.3649,5.0,2.416098,2.570632,2.416098,3.0,...,5.108914,2.726804,0.000000e+00,3323.964466,219.997778,2.207823,4.450128,317.792988,90.863709,62.080795
3,2023-01-04,Sector 62 Noida,182.754687,28.628,77.3649,6.0,1.111868,1.203726,1.111868,4.0,...,4.043421,2.261521,0.000000e+00,1015.261216,216.160108,2.966831,4.451210,310.775510,404.106163,166.872214
4,2023-01-05,Sector 62 Noida,259.587500,28.628,77.3649,5.0,1.452860,1.886003,1.452860,4.0,...,3.574554,2.451186,0.000000e+00,589.089737,176.133804,3.404987,4.451395,323.640444,72.879655,61.412179

In [7]:
df_prefinal.isnull().sum().compute()

date                        0
station_name                0
pm25                        0
latitude                    0
longitude                   0
n_pixels                 2993
AOD_mean                29921
AOD_max                 29921
AOD_p75                 29921
AOD_count                2993
AOD_coverage             2993
PBLH_mean                  92
PBLH_min                   92
PBLH_max                   92
TLML_mean                  92
TLML_max                   92
moisture_mean              92
moisture_max               92
SPEED_mean                 92
SPEED_min                  92
PRECTOT_sum                92
vent_coeff_mean            92
vent_coeff_min             92
inversion_proxy_mean       92
inversion_proxy_max        92
wind_dir_mean              92
PBLH_morning_mean          92
PBLH_morning_min           92
dtype: int64

In [8]:
df_prefinal = df_prefinal[df_prefinal["station_name"] != "Belur Math Howrah"]